/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bff/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trends */
        get: operations["list_trends_api_bff_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_bff_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/campaigns/{campaign_id}/kpi-defs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Campaign Kpi Defs
         * @description 캠페인의 KPI 정의 목록 조회
         */
        get: operations["read_campaign_kpi_defs_api_bff_campaigns__campaign_id__kpi_defs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/campaigns/{campaign_id}/kpi-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Campaign Kpi Results
         * @description 캠페인의 KPI 결과 목록 조회
         */
        get: operations["read_campaign_kpi_results_api_bff_campaigns__campaign_id__kpi_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Campaign
         * @description 특정 캠페인 조회
         */
        get: operations["read_campaign_api_bff_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Campaigns
         * @description 캠페인 목록 조회
         */
        get: operations["read_campaigns_api_bff_campaigns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/drafts/{draft_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Draft Variants
         * @description 드래프트의 플랫폼별 변형 목록 조회
         */
        get: operations["read_draft_variants_api_bff_drafts__draft_id__variants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Draft
         * @description 특정 드래프트 조회
         */
        get: operations["read_draft_api_bff_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Drafts
         * @description 드래프트 목록 조회
         */
        get: operations["read_drafts_api_bff_drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/accounts/platform/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Platform Account
         * @description 특정 플랫폼 계정 조회
         */
        get: operations["read_platform_account_api_bff_accounts_platform__account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/accounts/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Platform Accounts
         * @description 플랫폼 계정 목록 조회
         */
        get: operations["read_platform_accounts_api_bff_accounts_platform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/accounts/personas/{persona_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Persona
         * @description 특정 페르소나 조회
         */
        get: operations["read_persona_api_bff_accounts_personas__persona_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/accounts/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Personas
         * @description 페르소나 목록 조회
         */
        get: operations["read_personas_api_bff_accounts_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/accounts/personas/{persona_id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Accounts For Persona
         * @description 페르소나에 연결된 계정 목록 조회
         */
        get: operations["read_accounts_for_persona_api_bff_accounts_personas__persona_id__accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bff/accounts/platform/{account_id}/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Personas For Account
         * @description 계정에 연결된 페르소나 목록 조회
         */
        get: operations["read_personas_for_account_api_bff_accounts_platform__account_id__personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_orchestrator_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_orchestrator_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Campaign */
        post: operations["campaigns_create_campaign_api_orchestrator_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Campaign */
        put: operations["campaigns_update_campaign_api_orchestrator_campaigns__campaign_id__put"];
        post?: never;
        /** Delete Campaign */
        delete: operations["campaigns_delete_campaign_api_orchestrator_campaigns__campaign_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/campaigns/{campaign_id}/kpi-defs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert KPI Definitions */
        put: operations["campaigns_upsert_kpi_defs_api_orchestrator_campaigns__campaign_id__kpi_defs_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/campaigns/{campaign_id}/kpi-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record KPI Result */
        post: operations["campaigns_record_kpi_result_api_orchestrator_campaigns__campaign_id__kpi_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/campaigns/{campaign_id}/aggregate-kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aggregate KPI */
        post: operations["campaigns_aggregate_kpis_api_orchestrator_campaigns__campaign_id__aggregate_kpis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Draft */
        post: operations["drafts_create_api_orchestrator_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/drafts/{draft_id}/ir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Draft */
        put: operations["drafts_update_ir_api_orchestrator_drafts__draft_id__ir_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/accounts/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Platform Account */
        post: operations["accounts_platform_create_api_orchestrator_accounts_platform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/accounts/platform/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Platform Account */
        put: operations["accounts_platform_update_api_orchestrator_accounts_platform__account_id__put"];
        post?: never;
        /** Delete Platform Account */
        delete: operations["accounts_platform_delete_api_orchestrator_accounts_platform__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/accounts/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Persona */
        post: operations["accounts_persona_create_api_orchestrator_accounts_personas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/accounts/personas/{persona_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Persona */
        put: operations["accounts_persona_update_api_orchestrator_accounts_personas__persona_id__put"];
        post?: never;
        /** Delete Persona */
        delete: operations["accounts_persona_delete_api_orchestrator_accounts_personas__persona_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/accounts/persona-account-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Persona Account */
        post: operations["accounts_link_create_api_orchestrator_accounts_persona_account_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/accounts/persona-account-links/{persona_id}/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink Persona Account */
        delete: operations["accounts_link_delete_api_orchestrator_accounts_persona_account_links__persona_id___account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrator/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Insight */
        post: operations["insights_ingest_api_orchestrator_insights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aggregation
         * @enum {string}
         */
        Aggregation: "sum" | "last" | "avg";
        /** BlockImage */
        BlockImage: {
            /**
             * Type
             * @constant
             */
            type: "image";
            /** Props */
            props: {
                [key: string]: unknown;
            };
        };
        /** BlockText */
        BlockText: {
            /**
             * Type
             * @constant
             */
            type: "text";
            /** Props */
            props: {
                [key: string]: unknown;
            };
        };
        /** BlockVideo */
        BlockVideo: {
            /**
             * Type
             * @constant
             */
            type: "video";
            /** Props */
            props: {
                [key: string]: unknown;
            };
        };
        /** CampaignAggregationCommand */
        CampaignAggregationCommand: {
            /** Campaign Id */
            campaign_id?: number | null;
            /**
             * As Of
             * Format: date-time
             */
            as_of?: string | null;
        };
        /** CampaignCreate */
        CampaignCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Start At
             * Format: date-time
             */
            start_at?: string | null;
            /**
             * End At
             * Format: date-time
             */
            end_at?: string | null;
        };
        /** CampaignDeleteCommand */
        CampaignDeleteCommand: {
            /** Campaign Id */
            campaign_id?: number | null;
        };
        /** CampaignKPIDefListOut */
        CampaignKPIDefListOut: {
            /** Defs */
            defs: components["schemas"]["CampaignKPIDefOut"][];
        };
        /** CampaignKPIDefOut */
        CampaignKPIDefOut: {
            /** Id */
            id: number;
            /** Campaign Id */
            campaign_id: number;
            key: components["schemas"]["KPIKey"];
            aggregation: components["schemas"]["Aggregation"];
            /** Target Value */
            target_value?: number | null;
            /**
             * Weight
             * @default 1
             */
            weight: number;
        };
        /** CampaignKPIDefUpsert */
        CampaignKPIDefUpsert: {
            key: components["schemas"]["KPIKey"];
            /** @default sum */
            aggregation: components["schemas"]["Aggregation"];
            /** Target Value */
            target_value?: number | null;
            /**
             * Weight
             * @default 1
             */
            weight: number;
        };
        /** CampaignKPIDefUpsertCommand */
        CampaignKPIDefUpsertCommand: {
            /** Campaign Id */
            campaign_id?: number | null;
            /** Defs */
            defs: components["schemas"]["CampaignKPIDefUpsert"][];
        };
        /** CampaignKPIRecordCommand */
        CampaignKPIRecordCommand: {
            /** Campaign Id */
            campaign_id?: number | null;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /** CampaignKPIResultOut */
        CampaignKPIResultOut: {
            /** Id */
            id: number;
            /** Campaign Id */
            campaign_id: number;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /** CampaignOut */
        CampaignOut: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Start At
             * Format: date-time
             */
            start_at?: string | null;
            /**
             * End At
             * Format: date-time
             */
            end_at?: string | null;
            /** Id */
            id: number;
            /** Owner User Id */
            owner_user_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CampaignUpdateCommand */
        CampaignUpdateCommand: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Start At
             * Format: date-time
             */
            start_at?: string | null;
            /**
             * End At
             * Format: date-time
             */
            end_at?: string | null;
            /** Campaign Id */
            campaign_id?: number | null;
        };
        /** DraftIR */
        DraftIR: {
            /** Blocks */
            blocks: (components["schemas"]["BlockText"] | components["schemas"]["BlockImage"] | components["schemas"]["BlockVideo"])[];
            /** Options */
            options?: {
                [key: string]: unknown;
            };
        };
        /** DraftOut */
        DraftOut: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Campaign Id */
            campaign_id?: number | null;
            /** Title */
            title?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Goal */
            goal?: string | null;
            /** Ir */
            ir: {
                [key: string]: unknown;
            };
            /** Schema Version */
            schema_version: number;
            /** Ir Revision */
            ir_revision: number;
            /** State */
            state: string;
            /**
             * Monitoring Started At
             * Format: date-time
             */
            monitoring_started_at?: string | null;
            /**
             * Monitoring Ended At
             * Format: date-time
             */
            monitoring_ended_at?: string | null;
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DraftSaveRequest */
        DraftSaveRequest: {
            /** Campaign Id */
            campaign_id?: number | null;
            /** Title */
            title?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Goal */
            goal?: string | null;
            ir: components["schemas"]["DraftIR"];
        };
        /** DraftUpdateCommand */
        DraftUpdateCommand: {
            /** Draft Id */
            draft_id?: number | null;
            ir: components["schemas"]["DraftIR"];
            /** Title */
            title?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Goal */
            goal?: string | null;
            /** Campaign Id */
            campaign_id?: number | null;
        };
        /** DraftVariantOut */
        DraftVariantOut: {
            /** Id */
            id: number;
            /** Draft Id */
            draft_id: number;
            /** Platform */
            platform: string;
            /** Status */
            status: string;
            /** Errors */
            errors?: string[] | null;
            /** Warnings */
            warnings?: string[] | null;
            /** Rendered Caption */
            rendered_caption?: string | null;
            /** Rendered Blocks */
            rendered_blocks?: {
                [key: string]: unknown;
            } | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            } | null;
            /**
             * Compiled At
             * Format: date-time
             */
            compiled_at?: string | null;
            /** Ir Revision Compiled */
            ir_revision_compiled?: number | null;
            /** Compiler Version */
            compiler_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightInCommand */
        InsightInCommand: {
            /** Owner User Id */
            owner_user_id?: number | null;
            /** Draft Id */
            draft_id?: number | null;
            platform: components["schemas"]["PlatformKind"];
            /** Platform Post Id */
            platform_post_id?: string | null;
            /** Account Persona Id */
            account_persona_id?: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /**
             * Source
             * @default webhook
             * @enum {string}
             */
            source: "webhook" | "poll" | "manual";
            /** Ingest Key */
            ingest_key?: string | null;
        };
        /** InsightOut */
        InsightOut: {
            /** Owner User Id */
            owner_user_id: number;
            /** Draft Id */
            draft_id?: number | null;
            platform: components["schemas"]["PlatformKind"];
            /** Platform Post Id */
            platform_post_id?: string | null;
            /** Account Persona Id */
            account_persona_id?: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /**
             * Source
             * @default webhook
             * @enum {string}
             */
            source: "webhook" | "poll" | "manual";
            /** Ingest Key */
            ingest_key?: string | null;
            /** Id */
            id: number;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
        };
        /**
         * KPIKey
         * @enum {string}
         */
        KPIKey: "reach" | "impressions" | "likes" | "comments" | "shares" | "saves" | "follows" | "link_clicks" | "profile_visits" | "ctr" | "engagement_rate";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Message */
            message: string;
        };
        /**
         * NewsItem
         * @description 개별 뉴스 아이템 스키마
         */
        NewsItem: {
            /** News Item Title */
            news_item_title?: string | null;
            /** News Item Url */
            news_item_url?: string | null;
            /** News Item Picture */
            news_item_picture?: string | null;
            /** News Item Source */
            news_item_source?: string | null;
        };
        /**
         * Permission
         * @enum {string}
         */
        Permission: "read" | "write" | "publish";
        /** PersonaAccountLinkCommand */
        PersonaAccountLinkCommand: {
            link: components["schemas"]["PersonaAccountLinkCreate"];
        };
        /** PersonaAccountLinkCreate */
        PersonaAccountLinkCreate: {
            /** Persona Id */
            persona_id: number;
            /** Account Id */
            account_id: number;
            /**
             * Can Permissions
             * @default [
             *       "read",
             *       "publish",
             *       "write"
             *     ]
             */
            can_permissions: components["schemas"]["Permission"][] | null;
            /**
             * Is Verified Link
             * @default false
             */
            is_verified_link: boolean;
            /** Default Templates */
            default_templates?: {
                [key: string]: unknown;
            } | null;
        };
        /** PersonaAccountOut */
        PersonaAccountOut: {
            /** Id */
            id: number;
            /** Persona Id */
            persona_id: number;
            /** Account Id */
            account_id: number;
            /** Can Permissions */
            can_permissions: components["schemas"]["Permission"][];
            /** Is Verified Link */
            is_verified_link: boolean;
            /** Default Templates */
            default_templates?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PersonaAccountUnlinkCommand */
        PersonaAccountUnlinkCommand: {
            /** Persona Id */
            persona_id?: number | null;
            /** Account Id */
            account_id?: number | null;
        };
        /** PersonaCreateCommand */
        PersonaCreateCommand: {
            persona: components["schemas"]["PersonaCreatePayload"];
        };
        /** PersonaCreatePayload */
        PersonaCreatePayload: {
            /** Name */
            name: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Bio */
            bio?: string | null;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Tone */
            tone?: string | null;
            /** Style Guide */
            style_guide?: string | null;
            /** Pillars */
            pillars?: string[] | null;
            /** Banned Words */
            banned_words?: string[] | null;
            /** Default Hashtags */
            default_hashtags?: string[] | null;
            /** Hashtag Rules */
            hashtag_rules?: {
                [key: string]: unknown;
            } | null;
            /** Link Policy */
            link_policy?: {
                [key: string]: unknown;
            } | null;
            /** Media Prefs */
            media_prefs?: {
                [key: string]: unknown;
            } | null;
            /** Posting Windows */
            posting_windows?: {
                [key: string]: unknown;
            }[] | null;
            /** Extras */
            extras?: {
                [key: string]: unknown;
            } | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
        };
        /** PersonaDeleteCommand */
        PersonaDeleteCommand: {
            /** Persona Id */
            persona_id?: number | null;
        };
        /** PersonaOut */
        PersonaOut: {
            /** Name */
            name: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Bio */
            bio?: string | null;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Tone */
            tone?: string | null;
            /** Style Guide */
            style_guide?: string | null;
            /** Pillars */
            pillars?: string[] | null;
            /** Banned Words */
            banned_words?: string[] | null;
            /** Default Hashtags */
            default_hashtags?: string[] | null;
            /** Hashtag Rules */
            hashtag_rules?: {
                [key: string]: unknown;
            } | null;
            /** Link Policy */
            link_policy?: {
                [key: string]: unknown;
            } | null;
            /** Media Prefs */
            media_prefs?: {
                [key: string]: unknown;
            } | null;
            /** Posting Windows */
            posting_windows?: {
                [key: string]: unknown;
            }[] | null;
            /** Extras */
            extras?: {
                [key: string]: unknown;
            } | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PersonaUpdate */
        PersonaUpdate: {
            /** Name */
            name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Bio */
            bio?: string | null;
            /** Language */
            language?: string | null;
            /** Tone */
            tone?: string | null;
            /** Style Guide */
            style_guide?: string | null;
            /** Pillars */
            pillars?: string[] | null;
            /** Banned Words */
            banned_words?: string[] | null;
            /** Default Hashtags */
            default_hashtags?: string[] | null;
            /** Hashtag Rules */
            hashtag_rules?: {
                [key: string]: unknown;
            } | null;
            /** Link Policy */
            link_policy?: {
                [key: string]: unknown;
            } | null;
            /** Media Prefs */
            media_prefs?: {
                [key: string]: unknown;
            } | null;
            /** Posting Windows */
            posting_windows?: {
                [key: string]: unknown;
            }[] | null;
            /** Extras */
            extras?: {
                [key: string]: unknown;
            } | null;
            /** Schema Version */
            schema_version?: number | null;
        };
        /** PersonaUpdateCommand */
        PersonaUpdateCommand: {
            /** Persona Id */
            persona_id?: number | null;
            data: components["schemas"]["PersonaUpdate"];
        };
        /** PlatformAccountCreate */
        PlatformAccountCreate: {
            platform: components["schemas"]["PlatformKind"];
            /** Handle */
            handle: string;
            /** External Id */
            external_id?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Bio */
            bio?: string | null;
            /** Scopes */
            scopes?: string[] | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /** Access Token */
            access_token?: string | null;
            /** Refresh Token */
            refresh_token?: string | null;
            /**
             * Token Expires At
             * Format: date-time
             */
            token_expires_at?: string | null;
        };
        /** PlatformAccountCreateCommand */
        PlatformAccountCreateCommand: {
            account: components["schemas"]["PlatformAccountCreate"];
        };
        /** PlatformAccountDeleteCommand */
        PlatformAccountDeleteCommand: {
            /** Account Id */
            account_id?: number | null;
            /**
             * Soft
             * @default true
             */
            soft: boolean;
        };
        /** PlatformAccountOut */
        PlatformAccountOut: {
            platform: components["schemas"]["PlatformKind"];
            /** Handle */
            handle: string;
            /** External Id */
            external_id?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Bio */
            bio?: string | null;
            /** Scopes */
            scopes?: string[] | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /** Id */
            id: number;
            /** Owner User Id */
            owner_user_id: number;
            /**
             * Last Checked At
             * Format: date-time
             */
            last_checked_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlatformAccountUpdate */
        PlatformAccountUpdate: {
            /** Handle */
            handle?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Bio */
            bio?: string | null;
            /** Scopes */
            scopes?: string[] | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Access Token */
            access_token?: string | null;
            /** Refresh Token */
            refresh_token?: string | null;
            /**
             * Token Expires At
             * Format: date-time
             */
            token_expires_at?: string | null;
        };
        /** PlatformAccountUpdateCommand */
        PlatformAccountUpdateCommand: {
            /** Account Id */
            account_id?: number | null;
            data: components["schemas"]["PlatformAccountUpdate"];
        };
        /**
         * PlatformKind
         * @enum {string}
         */
        PlatformKind: "instagram" | "threads" | "x" | "blog";
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /**
         * TrendItem
         * @description Google Trends 개별 트렌드 아이템 스키마
         */
        TrendItem: {
            /**
             * Rank
             * @description 트렌드 순위
             */
            rank: number;
            /**
             * Retrieved
             * @description 데이터 수집 시각 (ISO format)
             */
            retrieved: string;
            /**
             * Title
             * @description 트렌드 키워드
             */
            title: string;
            /**
             * Approx Traffic
             * @description 대략적인 트래픽 (예: '200+', '1000+')
             */
            approx_traffic?: string | null;
            /**
             * Link
             * @description Google Trends 링크
             */
            link?: string | null;
            /**
             * Pubdate
             * @description 발행 날짜
             */
            pubDate?: string | null;
            /**
             * Picture
             * @description 대표 이미지 URL
             */
            picture?: string | null;
            /**
             * Picture Source
             * @description 이미지 출처
             */
            picture_source?: string | null;
            /**
             * News Item
             * @description 뉴스 아이템 (보통 빈 문자열)
             */
            news_item?: string | null;
            /**
             * News Items
             * @description 관련 뉴스 아이템 목록
             */
            news_items?: components["schemas"]["NewsItem"][] | null;
        } & {
            [key: string]: unknown;
        };
        /** TrendsListResponse */
        TrendsListResponse: {
            /**
             * Country
             * @description 국가 코드 (예: KR, US)
             */
            country: string;
            /**
             * Source
             * @description 데이터 소스 (예: cache, db, vector)
             * @enum {string}
             */
            source: "cache" | "db" | "vector";
            /**
             * Query
             * @description 키워드 (있으면 벡터 유사검색)
             */
            query?: string | null;
            /**
             * Items
             * @description 트렌드 아이템 목록
             */
            items: components["schemas"]["TrendItem"][];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_trends_api_bff_trends_get: {
        parameters: {
            query?: {
                country?: string;
                limit?: number;
                /** @description 검색 질의(벡터검색) */
                q?: string | null;
                /** @description YYYY-MM-DD (단일 일자) */
                on_date?: string | null;
                /** @description YYYY-MM-DD (이후/포함) */
                since?: string | null;
                /** @description YYYY-MM-DD (이전/포함) */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_bff_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    read_campaign_kpi_defs_api_bff_campaigns__campaign_id__kpi_defs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignKPIDefOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_campaign_kpi_results_api_bff_campaigns__campaign_id__kpi_results_get: {
        parameters: {
            query?: {
                /** @description 시작 날짜 */
                start?: string | null;
                /** @description 종료 날짜 */
                end?: string | null;
                /** @description 최대 항목 수 */
                limit?: number;
            };
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignKPIResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_campaign_api_bff_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_campaigns_api_bff_campaigns_get: {
        parameters: {
            query?: {
                /** @description 검색 쿼리 */
                q?: string | null;
                /** @description 페이지당 항목 수 */
                limit?: number;
                /** @description 오프셋 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_draft_variants_api_bff_drafts__draft_id__variants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftVariantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_draft_api_bff_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_drafts_api_bff_drafts_get: {
        parameters: {
            query?: {
                /** @description 캠페인 ID 필터 */
                campaign_id?: number | null;
                /** @description 페이지당 항목 수 */
                limit?: number;
                /** @description 오프셋 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_platform_account_api_bff_accounts_platform__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_platform_accounts_api_bff_accounts_platform_get: {
        parameters: {
            query?: {
                /** @description 플랫폼 필터 */
                platform?: components["schemas"]["PlatformKind"] | null;
                /** @description 핸들 검색 */
                handle?: string | null;
                /** @description 페이지당 항목 수 */
                limit?: number;
                /** @description 오프셋 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_persona_api_bff_accounts_personas__persona_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_personas_api_bff_accounts_personas_get: {
        parameters: {
            query?: {
                /** @description 이름 검색 */
                name?: string | null;
                /** @description 페이지당 항목 수 */
                limit?: number;
                /** @description 오프셋 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_accounts_for_persona_api_bff_accounts_personas__persona_id__accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaAccountOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_personas_for_account_api_bff_accounts_platform__account_id__personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaAccountOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_orchestrator_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_orchestrator_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaigns_create_campaign_api_orchestrator_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaigns_update_campaign_api_orchestrator_campaigns__campaign_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number | null;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignUpdateCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaigns_delete_campaign_api_orchestrator_campaigns__campaign_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number | null;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CampaignDeleteCommand"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaigns_upsert_kpi_defs_api_orchestrator_campaigns__campaign_id__kpi_defs_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number | null;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignKPIDefUpsertCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignKPIDefListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaigns_record_kpi_result_api_orchestrator_campaigns__campaign_id__kpi_results_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number | null;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignKPIRecordCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignKPIResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaigns_aggregate_kpis_api_orchestrator_campaigns__campaign_id__aggregate_kpis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number | null;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignAggregationCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignKPIResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drafts_create_api_orchestrator_drafts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drafts_update_ir_api_orchestrator_drafts__draft_id__ir_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number | null;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_platform_create_api_orchestrator_accounts_platform_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformAccountCreateCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_platform_update_api_orchestrator_accounts_platform__account_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number | null;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformAccountUpdateCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_platform_delete_api_orchestrator_accounts_platform__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number | null;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PlatformAccountDeleteCommand"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_persona_create_api_orchestrator_accounts_personas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaCreateCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_persona_update_api_orchestrator_accounts_personas__persona_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: number | null;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaUpdateCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_persona_delete_api_orchestrator_accounts_personas__persona_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: number | null;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PersonaDeleteCommand"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_link_create_api_orchestrator_accounts_persona_account_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaAccountLinkCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_link_delete_api_orchestrator_accounts_persona_account_links__persona_id___account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: number | null;
                account_id: number | null;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PersonaAccountUnlinkCommand"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_ingest_api_orchestrator_insights_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsightInCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
