/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Maestro Backend
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';

/**
 * @summary Signup
 */
export const signupApiAuthSignupPostBodyPasswordMin = 8;

export const signupApiAuthSignupPostBodyPasswordMax = 128;


export const signupApiAuthSignupPostBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(signupApiAuthSignupPostBodyPasswordMin).max(signupApiAuthSignupPostBodyPasswordMax),
  "display_name": zod.union([zod.string(),zod.null()]).optional()
})


/**
 * @summary Login
 */
export const loginApiAuthLoginPostBody = zod.object({
  "email": zod.email(),
  "password": zod.string()
})

export const loginApiAuthLoginPostResponseTokenTypeDefault = "bearer";

export const loginApiAuthLoginPostResponse = zod.object({
  "access_token": zod.string(),
  "token_type": zod.string().default(loginApiAuthLoginPostResponseTokenTypeDefault),
  "user": zod.object({
  "id": zod.number(),
  "email": zod.email(),
  "display_name": zod.union([zod.string(),zod.null()]).optional()
})
})


/**
 * @summary Me
 */
export const meApiMeGetResponse = zod.object({
  "id": zod.number(),
  "email": zod.email(),
  "display_name": zod.union([zod.string(),zod.null()]).optional()
})


/**
 * @summary Health
 */
export const healthApiHealthGetResponse = zod.any()
