/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Maestro Backend
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';

/**
 * Retrieve detailed information about a specific platform account for UI display
 * @summary Get Platform Account Details
 */
export const bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetParams = zod.object({
  "account_id": zod.number()
})

export const bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseHandleMax = 128;
export const bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseExternalIdMax = 256;
export const bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseAvatarUrlMax = 512;
export const bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseBioMax = 160;
export const bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseIsActiveDefault = true;

export const bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponse = zod.object({
  "owner_user_id": zod.number(),
  "platform": zod.enum(['instagram', 'threads', 'x', 'blog']),
  "handle": zod.string().max(bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseHandleMax),
  "external_id": zod.string().max(bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseExternalIdMax).nullish(),
  "avatar_url": zod.string().max(bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseAvatarUrlMax).nullish(),
  "bio": zod.string().max(bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseBioMax).nullish(),
  "scopes": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "is_active": zod.union([zod.boolean(),zod.null()]).default(bffAccountsReadPlatformAccountApiBffAccountsPlatformAccountIdGetResponseIsActiveDefault),
  "id": zod.number(),
  "last_checked_at": zod.iso.datetime({}).nullish(),
  "last_error": zod.string().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Get paginated list of all platform accounts for account management interface
 * @summary List All Platform Accounts
 */
export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetQueryLimitDefault = 50;export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetQueryOffsetDefault = 0;

export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetQueryParams = zod.object({
  "platform": zod.union([zod.enum(['instagram', 'threads', 'x', 'blog']),zod.null()]).optional(),
  "handle": zod.string().nullish(),
  "limit": zod.number().default(bffAccountsListPlatformAccountsApiBffAccountsPlatformGetQueryLimitDefault),
  "offset": zod.number().optional()
})

export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseHandleMax = 128;
export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseExternalIdMax = 256;
export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseAvatarUrlMax = 512;
export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseBioMax = 160;
export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseIsActiveDefault = true;

export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseItem = zod.object({
  "owner_user_id": zod.number(),
  "platform": zod.enum(['instagram', 'threads', 'x', 'blog']),
  "handle": zod.string().max(bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseHandleMax),
  "external_id": zod.string().max(bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseExternalIdMax).nullish(),
  "avatar_url": zod.string().max(bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseAvatarUrlMax).nullish(),
  "bio": zod.string().max(bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseBioMax).nullish(),
  "scopes": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "is_active": zod.union([zod.boolean(),zod.null()]).default(bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseIsActiveDefault),
  "id": zod.number(),
  "last_checked_at": zod.iso.datetime({}).nullish(),
  "last_error": zod.string().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponse = zod.array(bffAccountsListPlatformAccountsApiBffAccountsPlatformGetResponseItem)


/**
 * Retrieve detailed persona profile information for audience targeting setup
 * @summary Get Persona Profile Details
 */
export const bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetParams = zod.object({
  "persona_id": zod.number()
})

export const bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseNameMax = 100;
export const bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseAvatarUrlMax = 512;
export const bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseBioMax = 200;
export const bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseLanguageDefault = "en";
export const bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseLanguageMax = 10;
export const bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseToneMax = 40;
export const bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseSchemaVersionDefault = 1;

export const bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponse = zod.object({
  "name": zod.string().max(bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseNameMax),
  "avatar_url": zod.string().max(bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseAvatarUrlMax).nullish(),
  "bio": zod.string().max(bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseBioMax).nullish(),
  "language": zod.string().max(bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseLanguageMax).default(bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseLanguageDefault),
  "tone": zod.string().max(bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseToneMax).nullish(),
  "style_guide": zod.string().nullish(),
  "pillars": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "banned_words": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_hashtags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "hashtag_rules": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "link_policy": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "media_prefs": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "posting_windows": zod.union([zod.array(zod.record(zod.string(), zod.any())),zod.null()]).optional(),
  "extras": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "schema_version": zod.number().default(bffAccountsReadPersonaApiBffAccountsPersonasPersonaIdGetResponseSchemaVersionDefault),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Get paginated list of all persona profiles for campaign targeting configuration
 * @summary List All Persona Profiles
 */
export const bffAccountsListPersonasApiBffAccountsPersonasGetQueryLimitDefault = 50;export const bffAccountsListPersonasApiBffAccountsPersonasGetQueryOffsetDefault = 0;

export const bffAccountsListPersonasApiBffAccountsPersonasGetQueryParams = zod.object({
  "name": zod.string().nullish(),
  "limit": zod.number().default(bffAccountsListPersonasApiBffAccountsPersonasGetQueryLimitDefault),
  "offset": zod.number().optional()
})

export const bffAccountsListPersonasApiBffAccountsPersonasGetResponseNameMax = 100;
export const bffAccountsListPersonasApiBffAccountsPersonasGetResponseAvatarUrlMax = 512;
export const bffAccountsListPersonasApiBffAccountsPersonasGetResponseBioMax = 200;
export const bffAccountsListPersonasApiBffAccountsPersonasGetResponseLanguageDefault = "en";
export const bffAccountsListPersonasApiBffAccountsPersonasGetResponseLanguageMax = 10;
export const bffAccountsListPersonasApiBffAccountsPersonasGetResponseToneMax = 40;
export const bffAccountsListPersonasApiBffAccountsPersonasGetResponseSchemaVersionDefault = 1;

export const bffAccountsListPersonasApiBffAccountsPersonasGetResponseItem = zod.object({
  "name": zod.string().max(bffAccountsListPersonasApiBffAccountsPersonasGetResponseNameMax),
  "avatar_url": zod.string().max(bffAccountsListPersonasApiBffAccountsPersonasGetResponseAvatarUrlMax).nullish(),
  "bio": zod.string().max(bffAccountsListPersonasApiBffAccountsPersonasGetResponseBioMax).nullish(),
  "language": zod.string().max(bffAccountsListPersonasApiBffAccountsPersonasGetResponseLanguageMax).default(bffAccountsListPersonasApiBffAccountsPersonasGetResponseLanguageDefault),
  "tone": zod.string().max(bffAccountsListPersonasApiBffAccountsPersonasGetResponseToneMax).nullish(),
  "style_guide": zod.string().nullish(),
  "pillars": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "banned_words": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_hashtags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "hashtag_rules": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "link_policy": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "media_prefs": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "posting_windows": zod.union([zod.array(zod.record(zod.string(), zod.any())),zod.null()]).optional(),
  "extras": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "schema_version": zod.number().default(bffAccountsListPersonasApiBffAccountsPersonasGetResponseSchemaVersionDefault),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const bffAccountsListPersonasApiBffAccountsPersonasGetResponse = zod.array(bffAccountsListPersonasApiBffAccountsPersonasGetResponseItem)


/**
 * List all platform accounts connected to a specific persona for content distribution
 * @summary Get Platform Accounts for Persona
 */
export const bffAccountsListAccountsForPersonaApiBffAccountsPersonasPersonaIdAccountsGetParams = zod.object({
  "persona_id": zod.number()
})

export const bffAccountsListAccountsForPersonaApiBffAccountsPersonasPersonaIdAccountsGetResponseItem = zod.object({
  "id": zod.number(),
  "persona_id": zod.number(),
  "account_id": zod.number(),
  "can_permissions": zod.array(zod.enum(['read', 'write', 'publish'])),
  "is_verified_link": zod.boolean(),
  "default_templates": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const bffAccountsListAccountsForPersonaApiBffAccountsPersonasPersonaIdAccountsGetResponse = zod.array(bffAccountsListAccountsForPersonaApiBffAccountsPersonasPersonaIdAccountsGetResponseItem)


/**
 * List all personas linked to a specific platform account for targeted content strategy
 * @summary Get Personas for Platform Account
 */
export const bffAccountsListPersonasForAccountApiBffAccountsPlatformAccountIdPersonasGetParams = zod.object({
  "account_id": zod.number()
})

export const bffAccountsListPersonasForAccountApiBffAccountsPlatformAccountIdPersonasGetResponseItem = zod.object({
  "id": zod.number(),
  "persona_id": zod.number(),
  "account_id": zod.number(),
  "can_permissions": zod.array(zod.enum(['read', 'write', 'publish'])),
  "is_verified_link": zod.boolean(),
  "default_templates": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const bffAccountsListPersonasForAccountApiBffAccountsPlatformAccountIdPersonasGetResponse = zod.array(bffAccountsListPersonasForAccountApiBffAccountsPlatformAccountIdPersonasGetResponseItem)


/**
 * Retrieve complete campaign information for campaign management dashboard
 * @summary Get Campaign Details
 */
export const bffCampaignsReadCampaignApiBffCampaignsCampaignIdGetParams = zod.object({
  "campaign_id": zod.number()
})

export const bffCampaignsReadCampaignApiBffCampaignsCampaignIdGetResponseNameMax = 120;
export const bffCampaignsReadCampaignApiBffCampaignsCampaignIdGetResponseDescriptionMax = 500;


export const bffCampaignsReadCampaignApiBffCampaignsCampaignIdGetResponse = zod.object({
  "name": zod.string().max(bffCampaignsReadCampaignApiBffCampaignsCampaignIdGetResponseNameMax),
  "description": zod.string().max(bffCampaignsReadCampaignApiBffCampaignsCampaignIdGetResponseDescriptionMax).nullish(),
  "start_at": zod.iso.datetime({}).nullish(),
  "end_at": zod.iso.datetime({}).nullish(),
  "id": zod.number(),
  "owner_user_id": zod.number(),
  "created_at": zod.iso.datetime({})
})


/**
 * Get paginated list of all campaigns for campaign overview and management
 * @summary List All Campaigns
 */
export const bffCampaignsListCampaignsApiBffCampaignsGetQueryLimitDefault = 20;export const bffCampaignsListCampaignsApiBffCampaignsGetQueryOffsetDefault = 0;

export const bffCampaignsListCampaignsApiBffCampaignsGetQueryParams = zod.object({
  "q": zod.string().nullish(),
  "limit": zod.number().default(bffCampaignsListCampaignsApiBffCampaignsGetQueryLimitDefault),
  "offset": zod.number().optional()
})

export const bffCampaignsListCampaignsApiBffCampaignsGetResponseNameMax = 120;
export const bffCampaignsListCampaignsApiBffCampaignsGetResponseDescriptionMax = 500;


export const bffCampaignsListCampaignsApiBffCampaignsGetResponseItem = zod.object({
  "name": zod.string().max(bffCampaignsListCampaignsApiBffCampaignsGetResponseNameMax),
  "description": zod.string().max(bffCampaignsListCampaignsApiBffCampaignsGetResponseDescriptionMax).nullish(),
  "start_at": zod.iso.datetime({}).nullish(),
  "end_at": zod.iso.datetime({}).nullish(),
  "id": zod.number(),
  "owner_user_id": zod.number(),
  "created_at": zod.iso.datetime({})
})
export const bffCampaignsListCampaignsApiBffCampaignsGetResponse = zod.array(bffCampaignsListCampaignsApiBffCampaignsGetResponseItem)


/**
 * Retrieve all KPI definitions for a campaign to display metrics configuration
 * @summary Get Campaign KPI Definitions
 */
export const bffCampaignsListKpiDefsApiBffCampaignsCampaignIdKpiDefsGetParams = zod.object({
  "campaign_id": zod.number()
})

export const bffCampaignsListKpiDefsApiBffCampaignsCampaignIdKpiDefsGetResponseWeightDefault = 1;

export const bffCampaignsListKpiDefsApiBffCampaignsCampaignIdKpiDefsGetResponseItem = zod.object({
  "id": zod.number(),
  "campaign_id": zod.number(),
  "key": zod.enum(['reach', 'impressions', 'likes', 'comments', 'shares', 'saves', 'follows', 'link_clicks', 'profile_visits', 'ctr', 'engagement_rate']),
  "aggregation": zod.enum(['sum', 'last', 'avg']),
  "target_value": zod.union([zod.number(),zod.null()]).optional(),
  "weight": zod.number().default(bffCampaignsListKpiDefsApiBffCampaignsCampaignIdKpiDefsGetResponseWeightDefault)
})
export const bffCampaignsListKpiDefsApiBffCampaignsCampaignIdKpiDefsGetResponse = zod.array(bffCampaignsListKpiDefsApiBffCampaignsCampaignIdKpiDefsGetResponseItem)


/**
 * Retrieve KPI measurement results for campaign performance analytics and reporting
 * @summary Get Campaign KPI Results
 */
export const bffCampaignsListKpiResultsApiBffCampaignsCampaignIdKpiResultsGetParams = zod.object({
  "campaign_id": zod.number()
})

export const bffCampaignsListKpiResultsApiBffCampaignsCampaignIdKpiResultsGetQueryLimitDefault = 200;

export const bffCampaignsListKpiResultsApiBffCampaignsCampaignIdKpiResultsGetQueryParams = zod.object({
  "start": zod.iso.datetime({}).nullish(),
  "end": zod.iso.datetime({}).nullish(),
  "limit": zod.number().default(bffCampaignsListKpiResultsApiBffCampaignsCampaignIdKpiResultsGetQueryLimitDefault)
})

export const bffCampaignsListKpiResultsApiBffCampaignsCampaignIdKpiResultsGetResponseItem = zod.object({
  "id": zod.number(),
  "campaign_id": zod.number(),
  "as_of": zod.iso.datetime({}),
  "values": zod.record(zod.string(), zod.number())
})
export const bffCampaignsListKpiResultsApiBffCampaignsCampaignIdKpiResultsGetResponse = zod.array(bffCampaignsListKpiResultsApiBffCampaignsCampaignIdKpiResultsGetResponseItem)


/**
 * Get the current persona account for the user
 * @summary Get current persona account
 */
export const bffContextsCurrentPersonaAccountApiBffContextsPersonaAccountCurrentGetQueryParams = zod.object({
  "persona_account_id": zod.union([zod.number(),zod.null()]).optional()
})

export const bffContextsCurrentPersonaAccountApiBffContextsPersonaAccountCurrentGetResponse = zod.object({
  "id": zod.number(),
  "persona_id": zod.number(),
  "account_id": zod.number(),
  "can_permissions": zod.array(zod.enum(['read', 'write', 'publish'])),
  "is_verified_link": zod.boolean(),
  "default_templates": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})


/**
 * Get the current connected persona for the user
 * @summary Get current connected persona
 */
export const bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetQueryParams = zod.object({
  "persona_account_id": zod.union([zod.number(),zod.null()]).optional()
})

export const bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseNameMax = 100;
export const bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseAvatarUrlMax = 512;
export const bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseBioMax = 200;
export const bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseLanguageDefault = "en";
export const bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseLanguageMax = 10;
export const bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseToneMax = 40;
export const bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseSchemaVersionDefault = 1;

export const bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponse = zod.object({
  "name": zod.string().max(bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseNameMax),
  "avatar_url": zod.string().max(bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseAvatarUrlMax).nullish(),
  "bio": zod.string().max(bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseBioMax).nullish(),
  "language": zod.string().max(bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseLanguageMax).default(bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseLanguageDefault),
  "tone": zod.string().max(bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseToneMax).nullish(),
  "style_guide": zod.string().nullish(),
  "pillars": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "banned_words": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_hashtags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "hashtag_rules": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "link_policy": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "media_prefs": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "posting_windows": zod.union([zod.array(zod.record(zod.string(), zod.any())),zod.null()]).optional(),
  "extras": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "schema_version": zod.number().default(bffContextsCurrentPersonaApiBffContextsPersonaCurrentGetResponseSchemaVersionDefault),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Retrieve complete draft content and metadata for content editing interface
 * @summary Get Draft Content
 */
export const bffDraftsReadDraftApiBffDraftsDraftIdGetParams = zod.object({
  "draft_id": zod.number()
})

export const bffDraftsReadDraftApiBffDraftsDraftIdGetResponse = zod.object({
  "id": zod.number(),
  "user_id": zod.number(),
  "campaign_id": zod.union([zod.number(),zod.null()]).optional(),
  "title": zod.string().nullish(),
  "tags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "goal": zod.string().nullish(),
  "ir": zod.object({
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("text"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("image"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("video"),
  "props": zod.record(zod.string(), zod.any())
})])).min(1),
  "options": zod.record(zod.string(), zod.any()).optional()
}),
  "schema_version": zod.number(),
  "ir_revision": zod.number(),
  "state": zod.string(),
  "monitoring_started_at": zod.iso.datetime({}).nullish(),
  "monitoring_ended_at": zod.iso.datetime({}).nullish(),
  "created_by": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Get paginated list of all content drafts for content management dashboard
 * @summary List All Drafts
 */
export const bffDraftsListDraftsApiBffDraftsGetQueryLimitDefault = 20;export const bffDraftsListDraftsApiBffDraftsGetQueryOffsetDefault = 0;

export const bffDraftsListDraftsApiBffDraftsGetQueryParams = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()]).optional(),
  "limit": zod.number().default(bffDraftsListDraftsApiBffDraftsGetQueryLimitDefault),
  "offset": zod.number().optional()
})

export const bffDraftsListDraftsApiBffDraftsGetResponseItem = zod.object({
  "id": zod.number(),
  "user_id": zod.number(),
  "campaign_id": zod.union([zod.number(),zod.null()]).optional(),
  "title": zod.string().nullish(),
  "tags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "goal": zod.string().nullish(),
  "ir": zod.object({
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("text"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("image"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("video"),
  "props": zod.record(zod.string(), zod.any())
})])).min(1),
  "options": zod.record(zod.string(), zod.any()).optional()
}),
  "schema_version": zod.number(),
  "ir_revision": zod.number(),
  "state": zod.string(),
  "monitoring_started_at": zod.iso.datetime({}).nullish(),
  "monitoring_ended_at": zod.iso.datetime({}).nullish(),
  "created_by": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const bffDraftsListDraftsApiBffDraftsGetResponse = zod.array(bffDraftsListDraftsApiBffDraftsGetResponseItem)


/**
 * List all variants of a draft for content optimization and A/B testing
 * @summary Get Draft Variants
 */
export const bffDraftsListVariantsApiBffDraftsDraftIdVariantsGetParams = zod.object({
  "draft_id": zod.number()
})

export const bffDraftsListVariantsApiBffDraftsDraftIdVariantsGetResponseItem = zod.object({
  "id": zod.number(),
  "draft_id": zod.number(),
  "platform": zod.string(),
  "status": zod.string(),
  "errors": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "warnings": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "rendered_caption": zod.string().nullish(),
  "rendered_blocks": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "metrics": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "compiled_at": zod.iso.datetime({}).nullish(),
  "ir_revision_compiled": zod.union([zod.number(),zod.null()]).optional(),
  "compiler_version": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const bffDraftsListVariantsApiBffDraftsDraftIdVariantsGetResponse = zod.array(bffDraftsListVariantsApiBffDraftsDraftIdVariantsGetResponseItem)


/**
 * Retrieve authenticated user profile information for user interface and settings
 * @summary Get Current User Profile
 */
export const bffMeReadMeApiBffMeGetResponse = zod.object({
  "id": zod.number(),
  "email": zod.email(),
  "display_name": zod.string().nullish()
})


/**
 * Retrieve trend analysis data for content strategy and market insights dashboard
 * @summary Get Trend Analysis Data
 */
export const bffTrendsListTrendsApiBffTrendsGetQueryCountryDefault = "US";export const bffTrendsListTrendsApiBffTrendsGetQueryLimitDefault = 20;

export const bffTrendsListTrendsApiBffTrendsGetQueryParams = zod.object({
  "country": zod.string().default(bffTrendsListTrendsApiBffTrendsGetQueryCountryDefault),
  "limit": zod.number().default(bffTrendsListTrendsApiBffTrendsGetQueryLimitDefault),
  "q": zod.string().nullish(),
  "on_date": zod.iso.date().nullish(),
  "since": zod.iso.date().nullish(),
  "until": zod.iso.date().nullish()
})

export const bffTrendsListTrendsApiBffTrendsGetResponse = zod.object({
  "country": zod.string().describe('국가 코드 (예: KR, US)'),
  "source": zod.enum(['cache', 'db', 'vector']).describe('데이터 소스 (예: cache, db, vector)'),
  "query": zod.string().nullish().describe('키워드 (있으면 벡터 유사검색)'),
  "items": zod.array(zod.object({
  "rank": zod.number().describe('트렌드 순위'),
  "retrieved": zod.union([zod.string(),zod.iso.datetime({})]).describe('데이터 수집 시각 (ISO format)'),
  "title": zod.string().describe('트렌드 키워드'),
  "approx_traffic": zod.string().nullish().describe('대략적인 트래픽 (예: \'200+\', \'1000+\')'),
  "link": zod.string().nullish().describe('Google Trends 링크'),
  "pub_date": zod.string().nullish().describe('발행 날짜'),
  "picture": zod.string().nullish().describe('대표 이미지 URL'),
  "picture_source": zod.string().nullish().describe('이미지 출처'),
  "news_item": zod.string().nullish().describe('뉴스 아이템 (보통 빈 문자열)'),
  "news_items": zod.union([zod.array(zod.object({
  "news_item_title": zod.string().nullish(),
  "news_item_url": zod.string().nullish(),
  "news_item_picture": zod.string().nullish(),
  "news_item_source": zod.string().nullish()
}).describe('개별 뉴스 아이템 스키마')),zod.null()]).optional().describe('관련 뉴스 아이템 목록')
}).describe('Trends 개별 트렌드 아이템 스키마')).describe('트렌드 아이템 목록')
})


/**
 * Create a new platform account (social media, website, etc.) for the user
 * @summary Create New Platform Account
 */
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountHandleMax = 128;
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountExternalIdMax = 256;
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountAvatarUrlMax = 512;
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountBioMax = 160;
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountIsActiveDefault = true;

export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostBody = zod.object({
  "account": zod.object({
  "owner_user_id": zod.union([zod.number(),zod.null()]).optional(),
  "platform": zod.enum(['instagram', 'threads', 'x', 'blog']),
  "handle": zod.string().max(accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountHandleMax),
  "external_id": zod.string().max(accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountExternalIdMax).nullish(),
  "avatar_url": zod.string().max(accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountAvatarUrlMax).nullish(),
  "bio": zod.string().max(accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountBioMax).nullish(),
  "scopes": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "is_active": zod.union([zod.boolean(),zod.null()]).default(accountsPlatformCreateApiOrchestratorAccountsPlatformPostBodyAccountIsActiveDefault),
  "access_token": zod.string().nullish(),
  "refresh_token": zod.string().nullish(),
  "token_expires_at": zod.iso.datetime({}).nullish()
})
})

export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseHandleMax = 128;
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseExternalIdMax = 256;
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseAvatarUrlMax = 512;
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseBioMax = 160;
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseIsActiveDefault = true;

export const accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponse = zod.object({
  "owner_user_id": zod.number(),
  "platform": zod.enum(['instagram', 'threads', 'x', 'blog']),
  "handle": zod.string().max(accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseHandleMax),
  "external_id": zod.string().max(accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseExternalIdMax).nullish(),
  "avatar_url": zod.string().max(accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseAvatarUrlMax).nullish(),
  "bio": zod.string().max(accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseBioMax).nullish(),
  "scopes": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "is_active": zod.union([zod.boolean(),zod.null()]).default(accountsPlatformCreateApiOrchestratorAccountsPlatformPostResponseIsActiveDefault),
  "id": zod.number(),
  "last_checked_at": zod.iso.datetime({}).nullish(),
  "last_error": zod.string().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Update platform account information like username, credentials, or settings
 * @summary Update Platform Account Details
 */
export const accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutParams = zod.object({
  "account_id": zod.union([zod.number(),zod.null()])
})

export const accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutBody = zod.object({
  "account_id": zod.union([zod.number(),zod.null()]).optional(),
  "data": zod.object({
  "handle": zod.string().nullish(),
  "avatar_url": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "scopes": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "is_active": zod.union([zod.boolean(),zod.null()]).optional(),
  "access_token": zod.string().nullish(),
  "refresh_token": zod.string().nullish(),
  "token_expires_at": zod.iso.datetime({}).nullish()
})
})

export const accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseHandleMax = 128;
export const accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseExternalIdMax = 256;
export const accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseAvatarUrlMax = 512;
export const accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseBioMax = 160;
export const accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseIsActiveDefault = true;

export const accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponse = zod.object({
  "owner_user_id": zod.number(),
  "platform": zod.enum(['instagram', 'threads', 'x', 'blog']),
  "handle": zod.string().max(accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseHandleMax),
  "external_id": zod.string().max(accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseExternalIdMax).nullish(),
  "avatar_url": zod.string().max(accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseAvatarUrlMax).nullish(),
  "bio": zod.string().max(accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseBioMax).nullish(),
  "scopes": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "is_active": zod.union([zod.boolean(),zod.null()]).default(accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutResponseIsActiveDefault),
  "id": zod.number(),
  "last_checked_at": zod.iso.datetime({}).nullish(),
  "last_error": zod.string().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Permanently delete a platform account and all associated data
 * @summary Remove Platform Account
 */
export const accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteParams = zod.object({
  "account_id": zod.union([zod.number(),zod.null()])
})

export const accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteQuerySoftDefault = true;

export const accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteQueryParams = zod.object({
  "soft": zod.boolean().default(accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteQuerySoftDefault)
})

export const accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteResponse = zod.object({
  "message": zod.string()
})


/**
 * Create a new persona with specific characteristics for content targeting
 * @summary Create New Persona Profile
 */
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaNameMax = 100;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaAvatarUrlMax = 512;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaBioMax = 200;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaLanguageDefault = "en";
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaLanguageMax = 10;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaToneMax = 40;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaSchemaVersionDefault = 1;

export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostBody = zod.object({
  "persona": zod.object({
  "name": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaNameMax),
  "avatar_url": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaAvatarUrlMax).nullish(),
  "bio": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaBioMax).nullish(),
  "language": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaLanguageMax).default(accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaLanguageDefault),
  "tone": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaToneMax).nullish(),
  "style_guide": zod.string().nullish(),
  "pillars": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "banned_words": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_hashtags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "hashtag_rules": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "link_policy": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "media_prefs": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "posting_windows": zod.union([zod.array(zod.record(zod.string(), zod.any())),zod.null()]).optional(),
  "extras": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "schema_version": zod.number().default(accountsPersonaCreateApiOrchestratorAccountsPersonasPostBodyPersonaSchemaVersionDefault)
})
})

export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseNameMax = 100;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseAvatarUrlMax = 512;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseBioMax = 200;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseLanguageDefault = "en";
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseLanguageMax = 10;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseToneMax = 40;
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseSchemaVersionDefault = 1;

export const accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponse = zod.object({
  "name": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseNameMax),
  "avatar_url": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseAvatarUrlMax).nullish(),
  "bio": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseBioMax).nullish(),
  "language": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseLanguageMax).default(accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseLanguageDefault),
  "tone": zod.string().max(accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseToneMax).nullish(),
  "style_guide": zod.string().nullish(),
  "pillars": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "banned_words": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_hashtags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "hashtag_rules": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "link_policy": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "media_prefs": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "posting_windows": zod.union([zod.array(zod.record(zod.string(), zod.any())),zod.null()]).optional(),
  "extras": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "schema_version": zod.number().default(accountsPersonaCreateApiOrchestratorAccountsPersonasPostResponseSchemaVersionDefault),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Modify persona characteristics, demographics, or targeting preferences
 * @summary Update Persona Profile
 */
export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutParams = zod.object({
  "persona_id": zod.union([zod.number(),zod.null()])
})

export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutBody = zod.object({
  "persona_id": zod.union([zod.number(),zod.null()]).optional(),
  "data": zod.object({
  "name": zod.string().nullish(),
  "avatar_url": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "language": zod.string().nullish(),
  "tone": zod.string().nullish(),
  "style_guide": zod.string().nullish(),
  "pillars": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "banned_words": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_hashtags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "hashtag_rules": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "link_policy": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "media_prefs": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "posting_windows": zod.union([zod.array(zod.record(zod.string(), zod.any())),zod.null()]).optional(),
  "extras": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "schema_version": zod.union([zod.number(),zod.null()]).optional()
})
})

export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseNameMax = 100;
export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseAvatarUrlMax = 512;
export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseBioMax = 200;
export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseLanguageDefault = "en";
export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseLanguageMax = 10;
export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseToneMax = 40;
export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseSchemaVersionDefault = 1;

export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponse = zod.object({
  "name": zod.string().max(accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseNameMax),
  "avatar_url": zod.string().max(accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseAvatarUrlMax).nullish(),
  "bio": zod.string().max(accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseBioMax).nullish(),
  "language": zod.string().max(accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseLanguageMax).default(accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseLanguageDefault),
  "tone": zod.string().max(accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseToneMax).nullish(),
  "style_guide": zod.string().nullish(),
  "pillars": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "banned_words": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_hashtags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "hashtag_rules": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "link_policy": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "media_prefs": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "posting_windows": zod.union([zod.array(zod.record(zod.string(), zod.any())),zod.null()]).optional(),
  "extras": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "schema_version": zod.number().default(accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutResponseSchemaVersionDefault),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Permanently delete a persona and all associated targeting data
 * @summary Remove Persona Profile
 */
export const accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteParams = zod.object({
  "persona_id": zod.union([zod.number(),zod.null()])
})

export const accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteResponse = zod.object({
  "message": zod.string()
})


/**
 * Link a persona profile to a specific platform account for targeted content
 * @summary Connect Persona to Platform Account
 */
export const accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostBodyLinkCanPermissionsDefault = ["read", "publish", "write"];export const accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostBodyLinkIsVerifiedLinkDefault = false;

export const accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostBody = zod.object({
  "link": zod.object({
  "persona_id": zod.number(),
  "account_id": zod.number(),
  "can_permissions": zod.union([zod.array(zod.enum(['read', 'write', 'publish'])),zod.null()]).default(accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostBodyLinkCanPermissionsDefault),
  "is_verified_link": zod.boolean().optional(),
  "default_templates": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional()
})
})

export const accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostResponse = zod.object({
  "id": zod.number(),
  "persona_id": zod.number(),
  "account_id": zod.number(),
  "can_permissions": zod.array(zod.enum(['read', 'write', 'publish'])),
  "is_verified_link": zod.boolean(),
  "default_templates": zod.union([zod.record(zod.string(), zod.any()),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})


/**
 * Remove the connection between a persona and a platform account
 * @summary Disconnect Persona from Platform Account
 */
export const accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteParams = zod.object({
  "persona_id": zod.union([zod.number(),zod.null()]),
  "account_id": zod.union([zod.number(),zod.null()])
})

export const accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteResponse = zod.object({
  "message": zod.string()
})


/**
 * Set up a new marketing campaign with goals, timeline, and target audience
 * @summary Create New Marketing Campaign
 */
export const campaignsCreateCampaignApiOrchestratorCampaignsPostBodyNameMax = 120;
export const campaignsCreateCampaignApiOrchestratorCampaignsPostBodyDescriptionMax = 500;


export const campaignsCreateCampaignApiOrchestratorCampaignsPostBody = zod.object({
  "name": zod.string().max(campaignsCreateCampaignApiOrchestratorCampaignsPostBodyNameMax),
  "description": zod.string().max(campaignsCreateCampaignApiOrchestratorCampaignsPostBodyDescriptionMax).nullish(),
  "start_at": zod.iso.datetime({}).nullish(),
  "end_at": zod.iso.datetime({}).nullish()
})

export const campaignsCreateCampaignApiOrchestratorCampaignsPostResponseNameMax = 120;
export const campaignsCreateCampaignApiOrchestratorCampaignsPostResponseDescriptionMax = 500;


export const campaignsCreateCampaignApiOrchestratorCampaignsPostResponse = zod.object({
  "name": zod.string().max(campaignsCreateCampaignApiOrchestratorCampaignsPostResponseNameMax),
  "description": zod.string().max(campaignsCreateCampaignApiOrchestratorCampaignsPostResponseDescriptionMax).nullish(),
  "start_at": zod.iso.datetime({}).nullish(),
  "end_at": zod.iso.datetime({}).nullish(),
  "id": zod.number(),
  "owner_user_id": zod.number(),
  "created_at": zod.iso.datetime({})
})


/**
 * Modify campaign parameters like name, goals, timeline, or target audience
 * @summary Update Campaign Settings
 */
export const campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutParams = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()])
})

export const campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutBodyNameMax = 120;
export const campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutBodyDescriptionMax = 500;


export const campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutBody = zod.object({
  "name": zod.string().max(campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutBodyNameMax).nullish(),
  "description": zod.string().max(campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutBodyDescriptionMax).nullish(),
  "start_at": zod.iso.datetime({}).nullish(),
  "end_at": zod.iso.datetime({}).nullish(),
  "campaign_id": zod.union([zod.number(),zod.null()]).optional()
})

export const campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutResponseNameMax = 120;
export const campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutResponseDescriptionMax = 500;


export const campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutResponse = zod.object({
  "name": zod.string().max(campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutResponseNameMax),
  "description": zod.string().max(campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutResponseDescriptionMax).nullish(),
  "start_at": zod.iso.datetime({}).nullish(),
  "end_at": zod.iso.datetime({}).nullish(),
  "id": zod.number(),
  "owner_user_id": zod.number(),
  "created_at": zod.iso.datetime({})
})


/**
 * Permanently delete a campaign and all associated data
 * @summary Delete Campaign
 */
export const campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteParams = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()])
})

export const campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteResponse = zod.object({
  "message": zod.string()
})


/**
 * Set up or update Key Performance Indicators for campaign measurement
 * @summary Define Campaign KPIs
 */
export const campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutParams = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()])
})

export const campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutBodyDefsItemWeightDefault = 1;

export const campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutBody = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()]).optional(),
  "defs": zod.array(zod.object({
  "key": zod.enum(['reach', 'impressions', 'likes', 'comments', 'shares', 'saves', 'follows', 'link_clicks', 'profile_visits', 'ctr', 'engagement_rate']),
  "aggregation": zod.enum(['sum', 'last', 'avg']).optional(),
  "target_value": zod.union([zod.number(),zod.null()]).optional(),
  "weight": zod.number().default(campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutBodyDefsItemWeightDefault)
}))
})

export const campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutResponseDefsItemWeightDefault = 1;

export const campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutResponse = zod.object({
  "defs": zod.array(zod.object({
  "id": zod.number(),
  "campaign_id": zod.number(),
  "key": zod.enum(['reach', 'impressions', 'likes', 'comments', 'shares', 'saves', 'follows', 'link_clicks', 'profile_visits', 'ctr', 'engagement_rate']),
  "aggregation": zod.enum(['sum', 'last', 'avg']),
  "target_value": zod.union([zod.number(),zod.null()]).optional(),
  "weight": zod.number().default(campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutResponseDefsItemWeightDefault)
}))
})


/**
 * Log new KPI measurement data for campaign performance tracking
 * @summary Record Campaign KPI Data
 */
export const campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPostParams = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()])
})

export const campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPostBody = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()]).optional(),
  "as_of": zod.iso.datetime({}),
  "values": zod.record(zod.string(), zod.number())
})

export const campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPostResponse = zod.object({
  "id": zod.number(),
  "campaign_id": zod.number(),
  "as_of": zod.iso.datetime({}),
  "values": zod.record(zod.string(), zod.number())
})


/**
 * Aggregate and summarize KPI data for campaign performance analysis
 * @summary Calculate Campaign KPI Summary
 */
export const campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPostParams = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()])
})

export const campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPostBody = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()]).optional(),
  "as_of": zod.iso.datetime({}).nullish()
})

export const campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPostResponse = zod.object({
  "id": zod.number(),
  "campaign_id": zod.number(),
  "as_of": zod.iso.datetime({}),
  "values": zod.record(zod.string(), zod.number())
})


/**
 * Start a new content draft with initial parameters and metadata
 * @summary Create Content Draft
 */
export const draftsCreateApiOrchestratorDraftsPostBody = zod.object({
  "campaign_id": zod.union([zod.number(),zod.null()]).optional(),
  "title": zod.string().nullish(),
  "tags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "goal": zod.string().nullish(),
  "ir": zod.object({
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("text"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("image"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("video"),
  "props": zod.record(zod.string(), zod.any())
})])).min(1),
  "options": zod.record(zod.string(), zod.any()).optional()
})
})

export const draftsCreateApiOrchestratorDraftsPostResponse = zod.object({
  "id": zod.number(),
  "user_id": zod.number(),
  "campaign_id": zod.union([zod.number(),zod.null()]).optional(),
  "title": zod.string().nullish(),
  "tags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "goal": zod.string().nullish(),
  "ir": zod.object({
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("text"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("image"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("video"),
  "props": zod.record(zod.string(), zod.any())
})])).min(1),
  "options": zod.record(zod.string(), zod.any()).optional()
}),
  "schema_version": zod.number(),
  "ir_revision": zod.number(),
  "state": zod.string(),
  "monitoring_started_at": zod.iso.datetime({}).nullish(),
  "monitoring_ended_at": zod.iso.datetime({}).nullish(),
  "created_by": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Modify the content and structure of an existing draft
 * @summary Update Draft Content
 */
export const draftsUpdateIrApiOrchestratorDraftsDraftIdIrPutParams = zod.object({
  "draft_id": zod.union([zod.number(),zod.null()])
})

export const draftsUpdateIrApiOrchestratorDraftsDraftIdIrPutBody = zod.object({
  "draft_id": zod.union([zod.number(),zod.null()]).optional(),
  "ir": zod.object({
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("text"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("image"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("video"),
  "props": zod.record(zod.string(), zod.any())
})])).min(1),
  "options": zod.record(zod.string(), zod.any()).optional()
}),
  "title": zod.string().nullish(),
  "tags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "goal": zod.string().nullish(),
  "campaign_id": zod.union([zod.number(),zod.null()]).optional()
})

export const draftsUpdateIrApiOrchestratorDraftsDraftIdIrPutResponse = zod.object({
  "id": zod.number(),
  "user_id": zod.number(),
  "campaign_id": zod.union([zod.number(),zod.null()]).optional(),
  "title": zod.string().nullish(),
  "tags": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "goal": zod.string().nullish(),
  "ir": zod.object({
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("text"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("image"),
  "props": zod.record(zod.string(), zod.any())
}),zod.object({
  "type": zod.literal("video"),
  "props": zod.record(zod.string(), zod.any())
})])).min(1),
  "options": zod.record(zod.string(), zod.any()).optional()
}),
  "schema_version": zod.number(),
  "ir_revision": zod.number(),
  "state": zod.string(),
  "monitoring_started_at": zod.iso.datetime({}).nullish(),
  "monitoring_ended_at": zod.iso.datetime({}).nullish(),
  "created_by": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})


/**
 * Delete an existing draft
 * @summary Delete Draft
 */
export const draftsDeleteApiOrchestratorDraftsDraftIdDeleteParams = zod.object({
  "draft_id": zod.union([zod.number(),zod.null()])
})

export const draftsDeleteApiOrchestratorDraftsDraftIdDeleteResponse = zod.object({
  "message": zod.string()
})


/**
 * @summary Signup
 */
export const signupApiOrchestratorAuthSignupPostBodyPasswordMin = 8;

export const signupApiOrchestratorAuthSignupPostBodyPasswordMax = 128;


export const signupApiOrchestratorAuthSignupPostBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(signupApiOrchestratorAuthSignupPostBodyPasswordMin).max(signupApiOrchestratorAuthSignupPostBodyPasswordMax),
  "display_name": zod.string().nullish()
})


/**
 * @summary Login
 */
export const loginApiOrchestratorAuthLoginPostBody = zod.object({
  "email": zod.email(),
  "password": zod.string()
})

export const loginApiOrchestratorAuthLoginPostResponseTokenTypeDefault = "bearer";

export const loginApiOrchestratorAuthLoginPostResponse = zod.object({
  "access_token": zod.string(),
  "token_type": zod.string().default(loginApiOrchestratorAuthLoginPostResponseTokenTypeDefault),
  "user": zod.object({
  "id": zod.number(),
  "email": zod.email(),
  "display_name": zod.string().nullish()
})
})


/**
 * @summary Chat Query
 */
export const chatQueryApiOrchestratorChatQueryPostBody = zod.object({
  "message": zod.string().describe('User utterance (English)'),
  "session_id": zod.string().nullish().describe('Conversation identifier')
})

export const chatQueryApiOrchestratorChatQueryPostResponseIntentConfidenceDefault = 0;

export const chatQueryApiOrchestratorChatQueryPostResponse = zod.object({
  "intent": zod.object({
  "intent": zod.string(),
  "confidence": zod.number().optional(),
  "candidates": zod.array(zod.object({
  "intent": zod.string(),
  "confidence": zod.number()
})).optional(),
  "slots": zod.record(zod.string(), zod.any()).optional(),
  "raw_text": zod.string(),
  "keywords": zod.array(zod.string()).optional()
}).describe('Structured output describing an analysed user utterance.'),
  "match": zod.union([zod.object({
  "key": zod.string(),
  "title": zod.string(),
  "score": zod.number(),
  "strategy": zod.enum(['embedding', 'keyword']),
  "description": zod.string().nullish(),
  "tags": zod.array(zod.string()).optional()
}),zod.null()]).optional(),
  "alternative_matches": zod.array(zod.object({
  "key": zod.string(),
  "title": zod.string(),
  "score": zod.number(),
  "strategy": zod.enum(['embedding', 'keyword']),
  "description": zod.string().nullish(),
  "tags": zod.array(zod.string()).optional()
})).optional(),
  "plan_notes": zod.string().nullish(),
  "cards": zod.array(zod.object({
  "card_type": zod.string(),
  "data": zod.record(zod.string(), zod.any()),
  "title": zod.string().nullish(),
  "source_flow": zod.string().nullish()
})).optional(),
  "messages": zod.array(zod.string()).optional()
})


/**
 * Get list of all available flows.
 * @summary Get Available Flows
 */
export const getAvailableFlowsApiOrchestratorChatFlowsGetResponseItem = zod.object({
  "key": zod.string(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "method": zod.string(),
  "path": zod.string(),
  "tags": zod.array(zod.string())
})
export const getAvailableFlowsApiOrchestratorChatFlowsGetResponse = zod.array(getAvailableFlowsApiOrchestratorChatFlowsGetResponseItem)


/**
 * @summary Health
 */
export const healthApiHealthGetResponse = zod.any()
