"""Update models

Revision ID: 9b509ccc5594
Revises: 202412180001
Create Date: 2025-10-25 14:46:59.612787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b509ccc5594'
down_revision: Union[str, Sequence[str], None] = '202412180001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_kpi_results_as_of'), table_name='campaign_kpi_results')
    op.drop_index(op.f('ix_campaign_kpi_results_campaign_id'), table_name='campaign_kpi_results')
    op.drop_table('campaign_kpi_results')
    op.drop_index(op.f('ix_insight_draft_ts'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_kind_ts'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_platform_post_ts'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_pub_ts'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_account_persona_id'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_content_kind'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_draft_id'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_ingest_key'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_owner_user_id'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_platform'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_platform_post_id'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_post_publication_id'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_scope'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_source'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_ts'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_samples_variant_id'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_scope_ts'), table_name='insight_samples')
    op.drop_index(op.f('ix_insight_variant_ts'), table_name='insight_samples')
    op.drop_table('insight_samples')
    op.drop_index(op.f('idx_schedules_context'), table_name='schedules', postgresql_ops={'context': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_schedules_due_at'), table_name='schedules')
    op.drop_index(op.f('idx_schedules_persona_account_id'), table_name='schedules')
    op.drop_index(op.f('idx_schedules_status'), table_name='schedules')
    op.drop_index(op.f('idx_schedules_timeline_label'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_due_at'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_idempotency_key'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_queue'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_persona_accounts_account_id'), table_name='persona_accounts')
    op.drop_index(op.f('ix_persona_accounts_persona_id'), table_name='persona_accounts')
    op.drop_table('persona_accounts')
    op.drop_index(op.f('ix_post_publications_account_persona_id'), table_name='post_publications')
    op.drop_index(op.f('ix_post_publications_external_id'), table_name='post_publications')
    op.drop_index(op.f('ix_post_publications_platform'), table_name='post_publications')
    op.drop_index(op.f('ix_post_publications_status'), table_name='post_publications')
    op.drop_index(op.f('ix_post_publications_variant_id'), table_name='post_publications')
    op.drop_index(op.f('ix_pub_variant_account'), table_name='post_publications')
    op.drop_table('post_publications')
    op.drop_index(op.f('ix_trend_news_items_trend_id'), table_name='trend_news_items')
    op.drop_table('trend_news_items')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_owner_user_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_insight_comment_platform_post'), table_name='insight_comments')
    op.drop_index(op.f('ix_insight_comment_post_created'), table_name='insight_comments')
    op.drop_index(op.f('ix_insight_comments_account_persona_id'), table_name='insight_comments')
    op.drop_index(op.f('ix_insight_comments_ingested_at'), table_name='insight_comments')
    op.drop_index(op.f('ix_insight_comments_is_owned_by_me'), table_name='insight_comments')
    op.drop_index(op.f('ix_insight_comments_owner_user_id'), table_name='insight_comments')
    op.drop_index(op.f('ix_insight_comments_platform'), table_name='insight_comments')
    op.drop_index(op.f('ix_insight_comments_platform_post_id'), table_name='insight_comments')
    op.drop_index(op.f('ix_insight_comments_post_publication_id'), table_name='insight_comments')
    op.drop_table('insight_comments')
    op.drop_index(op.f('ix_playbooks_campaign_id'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_persona_id'), table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index(op.f('ix_reaction_rule_publications_is_active'), table_name='reaction_rule_publications')
    op.drop_index(op.f('ix_reaction_rule_publications_post_publication_id'), table_name='reaction_rule_publications')
    op.drop_index(op.f('ix_reaction_rule_publications_priority'), table_name='reaction_rule_publications')
    op.drop_index(op.f('ix_reaction_rule_publications_publication'), table_name='reaction_rule_publications')
    op.drop_index(op.f('ix_reaction_rule_publications_reaction_rule_id'), table_name='reaction_rule_publications')
    op.drop_table('reaction_rule_publications')
    op.drop_index(op.f('ix_platform_accounts_external_id'), table_name='platform_accounts')
    op.drop_index(op.f('ix_platform_accounts_handle'), table_name='platform_accounts')
    op.drop_index(op.f('ix_platform_accounts_owner_user_id'), table_name='platform_accounts')
    op.drop_index(op.f('ix_platform_accounts_platform'), table_name='platform_accounts')
    op.drop_index(op.f('ix_platform_handle'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_media_assets_draft_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_kind'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_owner_kind'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_owner_user_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_reaction_rule_keywords_is_active'), table_name='reaction_rule_keywords')
    op.drop_index(op.f('ix_reaction_rule_keywords_reaction_rule_id'), table_name='reaction_rule_keywords')
    op.drop_index(op.f('ix_reaction_rule_keywords_rule_tag'), table_name='reaction_rule_keywords')
    op.drop_index(op.f('ix_reaction_rule_keywords_tag_key'), table_name='reaction_rule_keywords')
    op.drop_table('reaction_rule_keywords')
    op.drop_index(op.f('ix_trends_country'), table_name='trends')
    op.drop_index(op.f('ix_trends_country_retrieved_rank'), table_name='trends')
    op.drop_index(op.f('ix_trends_rank'), table_name='trends')
    op.drop_index(op.f('ix_trends_retrieved'), table_name='trends')
    op.drop_index(op.f('ix_trends_title'), table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_reaction_action_logs_action_type'), table_name='reaction_action_logs')
    op.drop_index(op.f('ix_reaction_action_logs_comment'), table_name='reaction_action_logs')
    op.drop_index(op.f('ix_reaction_action_logs_insight_comment_id'), table_name='reaction_action_logs')
    op.drop_index(op.f('ix_reaction_action_logs_reaction_rule_id'), table_name='reaction_action_logs')
    op.drop_index(op.f('ix_reaction_action_logs_status'), table_name='reaction_action_logs')
    op.drop_index(op.f('ix_reaction_action_logs_tag_key'), table_name='reaction_action_logs')
    op.drop_table('reaction_action_logs')
    op.drop_index(op.f('ix_draft_media_draft_id'), table_name='draft_media')
    op.drop_index(op.f('ix_draft_media_kind'), table_name='draft_media')
    op.drop_index(op.f('ix_draft_media_owner_kind'), table_name='draft_media')
    op.drop_index(op.f('ix_draft_media_owner_user_id'), table_name='draft_media')
    op.drop_table('draft_media')
    op.drop_index(op.f('ix_reaction_rules_name'), table_name='reaction_rules')
    op.drop_index(op.f('ix_reaction_rules_owner_priority'), table_name='reaction_rules')
    op.drop_index(op.f('ix_reaction_rules_owner_user_id'), table_name='reaction_rules')
    op.drop_index(op.f('ix_reaction_rules_priority'), table_name='reaction_rules')
    op.drop_index(op.f('ix_reaction_rules_status'), table_name='reaction_rules')
    op.drop_table('reaction_rules')
    op.drop_index(op.f('ix_coworker_leases_owner_user_id'), table_name='coworker_leases')
    op.drop_table('coworker_leases')
    op.drop_index(op.f('ix_reaction_rule_actions_reaction_rule_id'), table_name='reaction_rule_actions')
    op.drop_index(op.f('ix_reaction_rule_actions_tag_key'), table_name='reaction_rule_actions')
    op.drop_table('reaction_rule_actions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ab_tests_campaign_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_persona_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_variant_a_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_variant_b_id'), table_name='ab_tests')
    op.drop_table('ab_tests')
    op.drop_index(op.f('ix_personas_name'), table_name='personas')
    op.drop_index(op.f('ix_personas_owner_user_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_reaction_message_templates_is_active'), table_name='reaction_message_templates')
    op.drop_index(op.f('ix_reaction_message_templates_owner'), table_name='reaction_message_templates')
    op.drop_index(op.f('ix_reaction_message_templates_owner_user_id'), table_name='reaction_message_templates')
    op.drop_index(op.f('ix_reaction_message_templates_persona_account_id'), table_name='reaction_message_templates')
    op.drop_index(op.f('ix_reaction_message_templates_tag_key'), table_name='reaction_message_templates')
    op.drop_index(op.f('ix_reaction_message_templates_template_type'), table_name='reaction_message_templates')
    op.drop_table('reaction_message_templates')
    op.drop_index(op.f('ix_reaction_alerts_insight_comment_id'), table_name='reaction_alerts')
    op.drop_index(op.f('ix_reaction_alerts_reaction_rule_id'), table_name='reaction_alerts')
    op.drop_index(op.f('ix_reaction_alerts_status'), table_name='reaction_alerts')
    op.drop_index(op.f('ix_reaction_alerts_tag_key'), table_name='reaction_alerts')
    op.drop_table('reaction_alerts')
    op.drop_index(op.f('ix_playbook_logs_playbook_id'), table_name='playbook_logs')
    op.drop_table('playbook_logs')
    op.drop_index(op.f('ix_draft_variants_draft_id'), table_name='draft_variants')
    op.drop_index(op.f('ix_draft_variants_platform'), table_name='draft_variants')
    op.drop_index(op.f('ix_draft_variants_status'), table_name='draft_variants')
    op.drop_index(op.f('ix_variant_draft_platform'), table_name='draft_variants')
    op.drop_table('draft_variants')
    op.drop_index(op.f('ix_campaign_kpi_defs_campaign_id'), table_name='campaign_kpi_defs')
    op.drop_index(op.f('ix_campaign_kpi_defs_key'), table_name='campaign_kpi_defs')
    op.drop_table('campaign_kpi_defs')
    op.drop_index(op.f('ix_drafts_campaign_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_created_by'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_state'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_user_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_user_state'), table_name='drafts')
    op.drop_table('drafts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('drafts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('goal', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('ir', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('schema_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ir_revision', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.ENUM('DRAFT', 'DELETED', name='draftstate'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='drafts_campaign_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='drafts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_drafts_user_state'), 'drafts', ['user_id', 'state'], unique=False)
    op.create_index(op.f('ix_drafts_user_id'), 'drafts', ['user_id'], unique=False)
    op.create_index(op.f('ix_drafts_state'), 'drafts', ['state'], unique=False)
    op.create_index(op.f('ix_drafts_created_by'), 'drafts', ['created_by'], unique=False)
    op.create_index(op.f('ix_drafts_campaign_id'), 'drafts', ['campaign_id'], unique=False)
    op.create_table('campaign_kpi_defs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key', postgresql.ENUM('REACH', 'IMPRESSIONS', 'LIKES', 'COMMENTS', 'SHARES', 'SAVES', 'FOLLOWS', 'LINK_CLICKS', 'PROFILE_VISITS', 'CTR', 'ER', name='kpikey'), autoincrement=False, nullable=False),
    sa.Column('target_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aggregation', postgresql.ENUM('SUM', 'LAST', 'AVG', name='aggregation'), autoincrement=False, nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('campaign_kpi_defs_campaign_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_kpi_defs_pkey'))
    )
    op.create_index(op.f('ix_campaign_kpi_defs_key'), 'campaign_kpi_defs', ['key'], unique=False)
    op.create_index(op.f('ix_campaign_kpi_defs_campaign_id'), 'campaign_kpi_defs', ['campaign_id'], unique=False)
    op.create_table('draft_variants',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('draft_variants_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', postgresql.ENUM('INSTAGRAM', 'THREADS', name='platformkind'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'VALID', 'INVALID', 'RENDERED', name='variantstatus'), autoincrement=False, nullable=False),
    sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('warnings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rendered_caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rendered_blocks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('compiled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ir_revision_compiled', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('compiler_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name='draft_variants_draft_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='draft_variants_pkey'),
    sa.UniqueConstraint('draft_id', 'platform', name='uq_variant_draft_platform', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_variant_draft_platform'), 'draft_variants', ['draft_id', 'platform'], unique=False)
    op.create_index(op.f('ix_draft_variants_status'), 'draft_variants', ['status'], unique=False)
    op.create_index(op.f('ix_draft_variants_platform'), 'draft_variants', ['platform'], unique=False)
    op.create_index(op.f('ix_draft_variants_draft_id'), 'draft_variants', ['draft_id'], unique=False)
    op.create_table('playbook_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('playbook_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('abtest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ref_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('persona_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trend_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('llm_input', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('llm_output', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('kpi_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], name=op.f('playbook_logs_playbook_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('playbook_logs_pkey'))
    )
    op.create_index(op.f('ix_playbook_logs_playbook_id'), 'playbook_logs', ['playbook_id'], unique=False)
    op.create_table('reaction_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reaction_rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('insight_comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('assignee_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'SKIPPED', name='reactionactionstatus'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolution_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['insight_comment_id'], ['insight_comments.id'], name=op.f('reaction_alerts_insight_comment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reaction_rule_id'], ['reaction_rules.id'], name=op.f('reaction_alerts_reaction_rule_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('reaction_alerts_pkey'))
    )
    op.create_index(op.f('ix_reaction_alerts_tag_key'), 'reaction_alerts', ['tag_key'], unique=False)
    op.create_index(op.f('ix_reaction_alerts_status'), 'reaction_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_reaction_alerts_reaction_rule_id'), 'reaction_alerts', ['reaction_rule_id'], unique=False)
    op.create_index(op.f('ix_reaction_alerts_insight_comment_id'), 'reaction_alerts', ['insight_comment_id'], unique=False)
    op.create_table('reaction_message_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('persona_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('template_type', postgresql.ENUM('DM', 'REPLY', 'ALERT', name='reactionactiontype'), autoincrement=False, nullable=False),
    sa.Column('tag_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('reaction_message_templates_pkey'))
    )
    op.create_index(op.f('ix_reaction_message_templates_template_type'), 'reaction_message_templates', ['template_type'], unique=False)
    op.create_index(op.f('ix_reaction_message_templates_tag_key'), 'reaction_message_templates', ['tag_key'], unique=False)
    op.create_index(op.f('ix_reaction_message_templates_persona_account_id'), 'reaction_message_templates', ['persona_account_id'], unique=False)
    op.create_index(op.f('ix_reaction_message_templates_owner_user_id'), 'reaction_message_templates', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_reaction_message_templates_owner'), 'reaction_message_templates', ['owner_user_id', 'template_type'], unique=False)
    op.create_index(op.f('ix_reaction_message_templates_is_active'), 'reaction_message_templates', ['is_active'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('personas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('tone', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('style_guide', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pillars', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('banned_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('default_hashtags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hashtag_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('link_policy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('media_prefs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('posting_windows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extras', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('schema_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='personas_pkey'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_persona_name_per_owner', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_personas_owner_user_id'), 'personas', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=False)
    op.create_table('ab_tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variable', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hypothesis', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('variant_a_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_b_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('winner_variant', postgresql.ENUM('VARIANT_A', 'VARIANT_B', name='abtestwinner'), autoincrement=False, nullable=True),
    sa.Column('uplift_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('ab_tests_campaign_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('ab_tests_persona_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_a_id'], ['drafts.id'], name=op.f('ab_tests_variant_a_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_b_id'], ['drafts.id'], name=op.f('ab_tests_variant_b_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_tests_pkey')),
    sa.UniqueConstraint('persona_id', 'campaign_id', 'variant_a_id', 'variant_b_id', name=op.f('uq_abtest_persona_campaign_variants'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ab_tests_variant_b_id'), 'ab_tests', ['variant_b_id'], unique=False)
    op.create_index(op.f('ix_ab_tests_variant_a_id'), 'ab_tests', ['variant_a_id'], unique=False)
    op.create_index(op.f('ix_ab_tests_persona_id'), 'ab_tests', ['persona_id'], unique=False)
    op.create_index(op.f('ix_ab_tests_campaign_id'), 'ab_tests', ['campaign_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reaction_rule_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reaction_rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('dm_template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reply_template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('alert_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('alert_assignee_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('llm_mode', postgresql.ENUM('TEMPLATE_ONLY', 'TEMPLATE_WITH_LLM_AUGMENT', name='reactionllmmode'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reaction_rule_id'], ['reaction_rules.id'], name=op.f('reaction_rule_actions_reaction_rule_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reaction_rule_actions_pkey')),
    sa.UniqueConstraint('reaction_rule_id', 'tag_key', name=op.f('uq_rule_action_tag'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reaction_rule_actions_tag_key'), 'reaction_rule_actions', ['tag_key'], unique=False)
    op.create_index(op.f('ix_reaction_rule_actions_reaction_rule_id'), 'reaction_rule_actions', ['reaction_rule_id'], unique=False)
    op.create_table('coworker_leases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('persona_account_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('interval_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('coworker_leases_pkey'))
    )
    op.create_index(op.f('ix_coworker_leases_owner_user_id'), 'coworker_leases', ['owner_user_id'], unique=True)
    op.create_table('reaction_rules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('reaction_rules_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', name='reactionrulestatus'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='reaction_rules_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_reaction_rules_status'), 'reaction_rules', ['status'], unique=False)
    op.create_index(op.f('ix_reaction_rules_priority'), 'reaction_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_reaction_rules_owner_user_id'), 'reaction_rules', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_reaction_rules_owner_priority'), 'reaction_rules', ['owner_user_id', 'priority'], unique=False)
    op.create_index(op.f('ix_reaction_rules_name'), 'reaction_rules', ['name'], unique=False)
    op.create_table('draft_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kind', postgresql.ENUM('IMAGE', 'VIDEO', name='filekind'), autoincrement=False, nullable=False),
    sa.Column('bucket', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('object_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('draft_media_draft_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('draft_media_pkey'))
    )
    op.create_index(op.f('ix_draft_media_owner_user_id'), 'draft_media', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_draft_media_owner_kind'), 'draft_media', ['owner_user_id', 'kind'], unique=False)
    op.create_index(op.f('ix_draft_media_kind'), 'draft_media', ['kind'], unique=False)
    op.create_index(op.f('ix_draft_media_draft_id'), 'draft_media', ['draft_id'], unique=False)
    op.create_table('reaction_action_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('insight_comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction_rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('action_type', postgresql.ENUM('DM', 'REPLY', 'ALERT', name='reactionactiontype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'SKIPPED', name='reactionactionstatus'), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['insight_comment_id'], ['insight_comments.id'], name=op.f('reaction_action_logs_insight_comment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reaction_rule_id'], ['reaction_rules.id'], name=op.f('reaction_action_logs_reaction_rule_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('reaction_action_logs_pkey')),
    sa.UniqueConstraint('insight_comment_id', 'tag_key', 'action_type', name=op.f('uq_reaction_action_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reaction_action_logs_tag_key'), 'reaction_action_logs', ['tag_key'], unique=False)
    op.create_index(op.f('ix_reaction_action_logs_status'), 'reaction_action_logs', ['status'], unique=False)
    op.create_index(op.f('ix_reaction_action_logs_reaction_rule_id'), 'reaction_action_logs', ['reaction_rule_id'], unique=False)
    op.create_index(op.f('ix_reaction_action_logs_insight_comment_id'), 'reaction_action_logs', ['insight_comment_id'], unique=False)
    op.create_index(op.f('ix_reaction_action_logs_comment'), 'reaction_action_logs', ['insight_comment_id', 'status'], unique=False)
    op.create_index(op.f('ix_reaction_action_logs_action_type'), 'reaction_action_logs', ['action_type'], unique=False)
    op.create_table('trends',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('trends_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('retrieved', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('approx_traffic', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pub_date', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('picture_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('news_item_raw', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trends_pkey'),
    sa.UniqueConstraint('country', 'retrieved', 'title', name='uq_trend_country_retrieved_title', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_trends_title'), 'trends', ['title'], unique=False)
    op.create_index(op.f('ix_trends_retrieved'), 'trends', ['retrieved'], unique=False)
    op.create_index(op.f('ix_trends_rank'), 'trends', ['rank'], unique=False)
    op.create_index(op.f('ix_trends_country_retrieved_rank'), 'trends', ['country', 'retrieved', 'rank'], unique=False)
    op.create_index(op.f('ix_trends_country'), 'trends', ['country'], unique=False)
    op.create_table('reaction_rule_keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reaction_rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('match_type', postgresql.ENUM('EXACT', 'CONTAINS', 'REGEX', name='reactionmatchtype'), autoincrement=False, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reaction_rule_id'], ['reaction_rules.id'], name=op.f('reaction_rule_keywords_reaction_rule_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reaction_rule_keywords_pkey')),
    sa.UniqueConstraint('reaction_rule_id', 'tag_key', 'keyword', name=op.f('uq_rule_tag_keyword'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reaction_rule_keywords_tag_key'), 'reaction_rule_keywords', ['tag_key'], unique=False)
    op.create_index(op.f('ix_reaction_rule_keywords_rule_tag'), 'reaction_rule_keywords', ['reaction_rule_id', 'tag_key'], unique=False)
    op.create_index(op.f('ix_reaction_rule_keywords_reaction_rule_id'), 'reaction_rule_keywords', ['reaction_rule_id'], unique=False)
    op.create_index(op.f('ix_reaction_rule_keywords_is_active'), 'reaction_rule_keywords', ['is_active'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('trace_parent', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('prompt_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('tokens_prompt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens_completion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_usage_pkey'))
    )
    op.create_table('media_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kind', postgresql.ENUM('IMAGE', 'VIDEO', name='filekind'), autoincrement=False, nullable=False),
    sa.Column('bucket', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('object_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('media_assets_draft_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('media_assets_pkey'))
    )
    op.create_index(op.f('ix_media_assets_owner_user_id'), 'media_assets', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_media_assets_owner_kind'), 'media_assets', ['owner_user_id', 'kind'], unique=False)
    op.create_index(op.f('ix_media_assets_kind'), 'media_assets', ['kind'], unique=False)
    op.create_index(op.f('ix_media_assets_draft_id'), 'media_assets', ['draft_id'], unique=False)
    op.create_table('platform_accounts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('platform_accounts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', postgresql.ENUM('INSTAGRAM', 'THREADS', name='platformkind'), autoincrement=False, nullable=False),
    sa.Column('handle', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='platform_accounts_pkey'),
    sa.UniqueConstraint('owner_user_id', 'platform', 'external_id', 'is_active', name='uq_platform_owner_external_active', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_platform_handle'), 'platform_accounts', ['platform', 'handle'], unique=False)
    op.create_index(op.f('ix_platform_accounts_platform'), 'platform_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_accounts_owner_user_id'), 'platform_accounts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_platform_accounts_handle'), 'platform_accounts', ['handle'], unique=False)
    op.create_index(op.f('ix_platform_accounts_external_id'), 'platform_accounts', ['external_id'], unique=False)
    op.create_table('reaction_rule_publications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reaction_rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_publication_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('active_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_publication_id'], ['post_publications.id'], name=op.f('reaction_rule_publications_post_publication_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reaction_rule_id'], ['reaction_rules.id'], name=op.f('reaction_rule_publications_reaction_rule_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reaction_rule_publications_pkey')),
    sa.UniqueConstraint('reaction_rule_id', 'post_publication_id', name=op.f('uq_rule_publication'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reaction_rule_publications_reaction_rule_id'), 'reaction_rule_publications', ['reaction_rule_id'], unique=False)
    op.create_index(op.f('ix_reaction_rule_publications_publication'), 'reaction_rule_publications', ['post_publication_id', 'priority'], unique=False)
    op.create_index(op.f('ix_reaction_rule_publications_priority'), 'reaction_rule_publications', ['priority'], unique=False)
    op.create_index(op.f('ix_reaction_rule_publications_post_publication_id'), 'reaction_rule_publications', ['post_publication_id'], unique=False)
    op.create_index(op.f('ix_reaction_rule_publications_is_active'), 'reaction_rule_publications', ['is_active'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aggregate_kpi', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('best_time_window', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('best_tone', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('top_hashtags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_event', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('playbooks_campaign_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('playbooks_persona_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('playbooks_pkey')),
    sa.UniqueConstraint('persona_id', 'campaign_id', name=op.f('uq_playbook_persona_campaign'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_playbooks_persona_id'), 'playbooks', ['persona_id'], unique=False)
    op.create_index(op.f('ix_playbooks_campaign_id'), 'playbooks', ['campaign_id'], unique=False)
    op.create_table('insight_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_publication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform', postgresql.ENUM('INSTAGRAM', 'THREADS', name='platformkind'), autoincrement=False, nullable=False),
    sa.Column('platform_post_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('account_persona_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_external_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('parent_external_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('author_username', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permalink', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('comment_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_owned_by_me', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_persona_id'], ['persona_accounts.id'], name=op.f('insight_comments_account_persona_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_publication_id'], ['post_publications.id'], name=op.f('insight_comments_post_publication_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('insight_comments_pkey')),
    sa.UniqueConstraint('platform', 'comment_external_id', name=op.f('uq_insight_comment_external'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_insight_comments_post_publication_id'), 'insight_comments', ['post_publication_id'], unique=False)
    op.create_index(op.f('ix_insight_comments_platform_post_id'), 'insight_comments', ['platform_post_id'], unique=False)
    op.create_index(op.f('ix_insight_comments_platform'), 'insight_comments', ['platform'], unique=False)
    op.create_index(op.f('ix_insight_comments_owner_user_id'), 'insight_comments', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_insight_comments_is_owned_by_me'), 'insight_comments', ['is_owned_by_me'], unique=False)
    op.create_index(op.f('ix_insight_comments_ingested_at'), 'insight_comments', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_insight_comments_account_persona_id'), 'insight_comments', ['account_persona_id'], unique=False)
    op.create_index(op.f('ix_insight_comment_post_created'), 'insight_comments', ['post_publication_id', 'comment_created_at'], unique=False)
    op.create_index(op.f('ix_insight_comment_platform_post'), 'insight_comments', ['platform', 'platform_post_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('campaigns_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='campaigns_pkey'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_campaign_name_owner', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_campaigns_owner_user_id'), 'campaigns', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_table('trend_news_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trend_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], name=op.f('trend_news_items_trend_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trend_news_items_pkey'))
    )
    op.create_index(op.f('ix_trend_news_items_trend_id'), 'trend_news_items', ['trend_id'], unique=False)
    op.create_table('post_publications',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('post_publications_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', postgresql.ENUM('INSTAGRAM', 'THREADS', name='platformkind'), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('permalink', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'SCHEDULED', 'PUBLISHED', 'DELETED', 'FAILED', 'CANCELLED', 'MONITORING', name='poststatus'), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('monitoring_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('monitoring_ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_polled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('warnings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_persona_id'], ['persona_accounts.id'], name='post_publications_account_persona_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['draft_variants.id'], name='post_publications_variant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='post_publications_pkey'),
    sa.UniqueConstraint('platform', 'account_persona_id', 'external_id', name='uq_pub_account_external', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_pub_variant_account'), 'post_publications', ['variant_id', 'account_persona_id'], unique=False)
    op.create_index(op.f('ix_post_publications_variant_id'), 'post_publications', ['variant_id'], unique=False)
    op.create_index(op.f('ix_post_publications_status'), 'post_publications', ['status'], unique=False)
    op.create_index(op.f('ix_post_publications_platform'), 'post_publications', ['platform'], unique=False)
    op.create_index(op.f('ix_post_publications_external_id'), 'post_publications', ['external_id'], unique=False)
    op.create_index(op.f('ix_post_publications_account_persona_id'), 'post_publications', ['account_persona_id'], unique=False)
    op.create_table('persona_accounts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('persona_accounts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('can_permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_verified_link', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('default_templates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], name='persona_accounts_account_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name='persona_accounts_persona_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='persona_accounts_pkey'),
    sa.UniqueConstraint('persona_id', 'account_id', name='uq_persona_account', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_persona_accounts_persona_id'), 'persona_accounts', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_accounts_account_id'), 'persona_accounts', ['account_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('persona_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('queue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dag_spec', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['persona_account_id'], ['persona_accounts.id'], name=op.f('schedules_persona_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('schedules_pkey'))
    )
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_index(op.f('ix_schedules_queue'), 'schedules', ['queue'], unique=False)
    op.create_index(op.f('ix_schedules_idempotency_key'), 'schedules', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_schedules_due_at'), 'schedules', ['due_at'], unique=False)
    op.create_index(op.f('idx_schedules_timeline_label'), 'schedules', [sa.literal_column("(context ->> 'template'::text)")], unique=False)
    op.create_index(op.f('idx_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_index(op.f('idx_schedules_persona_account_id'), 'schedules', ['persona_account_id'], unique=False)
    op.create_index(op.f('idx_schedules_due_at'), 'schedules', ['due_at'], unique=False)
    op.create_index(op.f('idx_schedules_context'), 'schedules', ['context'], unique=False, postgresql_ops={'context': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_table('insight_samples',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_publication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform', postgresql.ENUM('INSTAGRAM', 'THREADS', name='platformkind'), autoincrement=False, nullable=False),
    sa.Column('platform_post_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('account_persona_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('content_kind', postgresql.ENUM('POST', 'VIDEO', 'STORY', 'CAROUSEL', 'LIVE', 'UNKNOWN', name='contentkind'), autoincrement=False, nullable=False),
    sa.Column('scope', postgresql.ENUM('LIFETIME', 'SINCE_PUBLISH', 'INTERVAL', name='metricsscope'), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ingest_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('source', postgresql.ENUM('WEBHOOK', 'POLL', 'MANUAL', name='insightsource'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_persona_id'], ['persona_accounts.id'], name=op.f('insight_samples_account_persona_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('insight_samples_draft_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_publication_id'], ['post_publications.id'], name=op.f('insight_samples_post_publication_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['draft_variants.id'], name=op.f('insight_samples_variant_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('insight_samples_pkey')),
    sa.UniqueConstraint('platform', 'platform_post_id', 'ts', name=op.f('uq_insight_post_ts'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_insight_variant_ts'), 'insight_samples', ['variant_id', 'ts'], unique=False)
    op.create_index(op.f('ix_insight_scope_ts'), 'insight_samples', ['scope', 'ts'], unique=False)
    op.create_index(op.f('ix_insight_samples_variant_id'), 'insight_samples', ['variant_id'], unique=False)
    op.create_index(op.f('ix_insight_samples_ts'), 'insight_samples', ['ts'], unique=False)
    op.create_index(op.f('ix_insight_samples_source'), 'insight_samples', ['source'], unique=False)
    op.create_index(op.f('ix_insight_samples_scope'), 'insight_samples', ['scope'], unique=False)
    op.create_index(op.f('ix_insight_samples_post_publication_id'), 'insight_samples', ['post_publication_id'], unique=False)
    op.create_index(op.f('ix_insight_samples_platform_post_id'), 'insight_samples', ['platform_post_id'], unique=False)
    op.create_index(op.f('ix_insight_samples_platform'), 'insight_samples', ['platform'], unique=False)
    op.create_index(op.f('ix_insight_samples_owner_user_id'), 'insight_samples', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_insight_samples_ingest_key'), 'insight_samples', ['ingest_key'], unique=True)
    op.create_index(op.f('ix_insight_samples_draft_id'), 'insight_samples', ['draft_id'], unique=False)
    op.create_index(op.f('ix_insight_samples_content_kind'), 'insight_samples', ['content_kind'], unique=False)
    op.create_index(op.f('ix_insight_samples_account_persona_id'), 'insight_samples', ['account_persona_id'], unique=False)
    op.create_index(op.f('ix_insight_pub_ts'), 'insight_samples', ['post_publication_id', 'ts'], unique=False)
    op.create_index(op.f('ix_insight_platform_post_ts'), 'insight_samples', ['platform', 'platform_post_id', 'ts'], unique=False)
    op.create_index(op.f('ix_insight_kind_ts'), 'insight_samples', ['content_kind', 'ts'], unique=False)
    op.create_index(op.f('ix_insight_draft_ts'), 'insight_samples', ['draft_id', 'ts'], unique=False)
    op.create_table('campaign_kpi_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('as_of', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('campaign_kpi_results_campaign_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_kpi_results_pkey'))
    )
    op.create_index(op.f('ix_campaign_kpi_results_campaign_id'), 'campaign_kpi_results', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_kpi_results_as_of'), 'campaign_kpi_results', ['as_of'], unique=False)
    # ### end Alembic commands ###
