/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Maestro Backend
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiFetch } from './fetcher';
export type Aggregation = typeof Aggregation[keyof typeof Aggregation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Aggregation = {
  sum: 'sum',
  last: 'last',
  avg: 'avg',
} as const;

export type BlockImageProps = { [key: string]: unknown };

export interface BlockImage {
  type: 'image';
  props: BlockImageProps;
}

export type BlockTextProps = { [key: string]: unknown };

export interface BlockText {
  type: 'text';
  props: BlockTextProps;
}

export type BlockVideoProps = { [key: string]: unknown };

export interface BlockVideo {
  type: 'video';
  props: BlockVideoProps;
}

export type CampaignAggregationCommandCampaignId = number | null;

export interface CampaignAggregationCommand {
  campaign_id?: CampaignAggregationCommandCampaignId;
  /** @nullable */
  as_of?: string | null;
}

export interface CampaignCreate {
  /** @maxLength 120 */
  name: string;
  /**
   * @maxLength 500
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  start_at?: string | null;
  /** @nullable */
  end_at?: string | null;
}

export type CampaignDeleteCommandCampaignId = number | null;

export interface CampaignDeleteCommand {
  campaign_id?: CampaignDeleteCommandCampaignId;
}

export interface CampaignKPIDefListOut {
  defs: CampaignKPIDefOut[];
}

export type CampaignKPIDefOutTargetValue = number | null;

export interface CampaignKPIDefOut {
  id: number;
  campaign_id: number;
  key: KPIKey;
  aggregation: Aggregation;
  target_value?: CampaignKPIDefOutTargetValue;
  weight?: number;
}

export type CampaignKPIDefUpsertTargetValue = number | null;

export interface CampaignKPIDefUpsert {
  key: KPIKey;
  aggregation?: Aggregation;
  target_value?: CampaignKPIDefUpsertTargetValue;
  weight?: number;
}

export type CampaignKPIDefUpsertCommandCampaignId = number | null;

export interface CampaignKPIDefUpsertCommand {
  campaign_id?: CampaignKPIDefUpsertCommandCampaignId;
  defs: CampaignKPIDefUpsert[];
}

export type CampaignKPIRecordCommandCampaignId = number | null;

export type CampaignKPIRecordCommandValues = {[key: string]: number};

export interface CampaignKPIRecordCommand {
  campaign_id?: CampaignKPIRecordCommandCampaignId;
  as_of: string;
  values: CampaignKPIRecordCommandValues;
}

export type CampaignKPIResultOutValues = {[key: string]: number};

export interface CampaignKPIResultOut {
  id: number;
  campaign_id: number;
  as_of: string;
  values: CampaignKPIResultOutValues;
}

export interface CampaignOut {
  /** @maxLength 120 */
  name: string;
  /**
   * @maxLength 500
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  start_at?: string | null;
  /** @nullable */
  end_at?: string | null;
  id: number;
  owner_user_id: number;
  created_at: string;
}

export type CampaignUpdateCommandCampaignId = number | null;

export interface CampaignUpdateCommand {
  /**
   * @maxLength 120
   * @nullable
   */
  name?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  start_at?: string | null;
  /** @nullable */
  end_at?: string | null;
  campaign_id?: CampaignUpdateCommandCampaignId;
}

export type ChatCardData = { [key: string]: unknown };

export interface ChatCard {
  card_type: string;
  data: ChatCardData;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  source_flow?: string | null;
}

export interface ChatQuery {
  /** User utterance (English) */
  message: string;
  /**
   * Conversation identifier
   * @nullable
   */
  session_id?: string | null;
}

export interface ChatResponse {
  intent: IntentResult;
  /** @nullable */
  plan_notes?: string | null;
  cards?: ChatCard[];
  messages?: string[];
}

export type DraftIRBlocksItem = BlockText | BlockImage | BlockVideo;

export type DraftIROptions = { [key: string]: unknown };

export interface DraftIR {
  /** @minItems 1 */
  blocks: DraftIRBlocksItem[];
  options?: DraftIROptions;
}

export type DraftOutCampaignId = number | null;

export type DraftOutTags = string[] | null;

export type DraftOutIr = { [key: string]: unknown };

export interface DraftOut {
  id: number;
  user_id: number;
  campaign_id?: DraftOutCampaignId;
  /** @nullable */
  title?: string | null;
  tags?: DraftOutTags;
  /** @nullable */
  goal?: string | null;
  ir: DraftOutIr;
  schema_version: number;
  ir_revision: number;
  state: string;
  /** @nullable */
  monitoring_started_at?: string | null;
  /** @nullable */
  monitoring_ended_at?: string | null;
  created_by: number;
  created_at: string;
  updated_at: string;
}

export type DraftSaveRequestCampaignId = number | null;

export type DraftSaveRequestTags = string[] | null;

export interface DraftSaveRequest {
  campaign_id?: DraftSaveRequestCampaignId;
  /** @nullable */
  title?: string | null;
  tags?: DraftSaveRequestTags;
  /** @nullable */
  goal?: string | null;
  ir: DraftIR;
}

export type DraftUpdateCommandDraftId = number | null;

export type DraftUpdateCommandTags = string[] | null;

export type DraftUpdateCommandCampaignId = number | null;

export interface DraftUpdateCommand {
  draft_id?: DraftUpdateCommandDraftId;
  ir: DraftIR;
  /** @nullable */
  title?: string | null;
  tags?: DraftUpdateCommandTags;
  /** @nullable */
  goal?: string | null;
  campaign_id?: DraftUpdateCommandCampaignId;
}

export interface FlowInfo {
  key: string;
  title: string;
  /** @nullable */
  description?: string | null;
  method: string;
  path: string;
  tags: string[];
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type InsightInCommandOwnerUserId = number | null;

export type InsightInCommandDraftId = number | null;

export type InsightInCommandAccountPersonaId = number | null;

export type InsightInCommandMetrics = {[key: string]: number};

export type InsightInCommandSource = typeof InsightInCommandSource[keyof typeof InsightInCommandSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InsightInCommandSource = {
  webhook: 'webhook',
  poll: 'poll',
  manual: 'manual',
} as const;

export interface InsightInCommand {
  owner_user_id?: InsightInCommandOwnerUserId;
  draft_id?: InsightInCommandDraftId;
  platform: PlatformKind;
  /** @nullable */
  platform_post_id?: string | null;
  account_persona_id?: InsightInCommandAccountPersonaId;
  ts: string;
  metrics?: InsightInCommandMetrics;
  source?: InsightInCommandSource;
  /** @nullable */
  ingest_key?: string | null;
}

export type InsightOutDraftId = number | null;

export type InsightOutAccountPersonaId = number | null;

export type InsightOutMetrics = {[key: string]: number};

export type InsightOutSource = typeof InsightOutSource[keyof typeof InsightOutSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InsightOutSource = {
  webhook: 'webhook',
  poll: 'poll',
  manual: 'manual',
} as const;

export interface InsightOut {
  owner_user_id: number;
  draft_id?: InsightOutDraftId;
  platform: PlatformKind;
  /** @nullable */
  platform_post_id?: string | null;
  account_persona_id?: InsightOutAccountPersonaId;
  ts: string;
  metrics?: InsightOutMetrics;
  source?: InsightOutSource;
  /** @nullable */
  ingest_key?: string | null;
  id: number;
  ingested_at: string;
}

export interface IntentCandidate {
  intent: string;
  confidence: number;
}

export type IntentResultSlots = { [key: string]: unknown };

/**
 * Structured output describing an analysed user utterance.
 */
export interface IntentResult {
  intent: string;
  confidence?: number;
  candidates?: IntentCandidate[];
  slots?: IntentResultSlots;
  raw_text: string;
  keywords?: string[];
}

export type KPIKey = typeof KPIKey[keyof typeof KPIKey];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KPIKey = {
  reach: 'reach',
  impressions: 'impressions',
  likes: 'likes',
  comments: 'comments',
  shares: 'shares',
  saves: 'saves',
  follows: 'follows',
  link_clicks: 'link_clicks',
  profile_visits: 'profile_visits',
  ctr: 'ctr',
  engagement_rate: 'engagement_rate',
} as const;

export interface LoginRequest {
  email: string;
  password: string;
}

export interface MessageOut {
  message: string;
}

export type Permission = typeof Permission[keyof typeof Permission];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Permission = {
  read: 'read',
  write: 'write',
  publish: 'publish',
} as const;

export interface PersonaAccountLinkCommand {
  link: PersonaAccountLinkCreate;
}

export type PersonaAccountLinkCreateCanPermissions = Permission[] | null;

export type PersonaAccountLinkCreateDefaultTemplatesAnyOf = { [key: string]: unknown };

export type PersonaAccountLinkCreateDefaultTemplates = PersonaAccountLinkCreateDefaultTemplatesAnyOf | null;

export interface PersonaAccountLinkCreate {
  persona_id: number;
  account_id: number;
  can_permissions?: PersonaAccountLinkCreateCanPermissions;
  is_verified_link?: boolean;
  default_templates?: PersonaAccountLinkCreateDefaultTemplates;
}

export type PersonaAccountOutDefaultTemplatesAnyOf = { [key: string]: unknown };

export type PersonaAccountOutDefaultTemplates = PersonaAccountOutDefaultTemplatesAnyOf | null;

export interface PersonaAccountOut {
  id: number;
  persona_id: number;
  account_id: number;
  can_permissions: Permission[];
  is_verified_link: boolean;
  default_templates?: PersonaAccountOutDefaultTemplates;
  created_at: string;
}

export type PersonaAccountUnlinkCommandPersonaId = number | null;

export type PersonaAccountUnlinkCommandAccountId = number | null;

export interface PersonaAccountUnlinkCommand {
  persona_id?: PersonaAccountUnlinkCommandPersonaId;
  account_id?: PersonaAccountUnlinkCommandAccountId;
}

export interface PersonaCreateCommand {
  persona: PersonaCreatePayload;
}

export type PersonaCreatePayloadPillars = string[] | null;

export type PersonaCreatePayloadBannedWords = string[] | null;

export type PersonaCreatePayloadDefaultHashtags = string[] | null;

export type PersonaCreatePayloadHashtagRulesAnyOf = { [key: string]: unknown };

export type PersonaCreatePayloadHashtagRules = PersonaCreatePayloadHashtagRulesAnyOf | null;

export type PersonaCreatePayloadLinkPolicyAnyOf = { [key: string]: unknown };

export type PersonaCreatePayloadLinkPolicy = PersonaCreatePayloadLinkPolicyAnyOf | null;

export type PersonaCreatePayloadMediaPrefsAnyOf = { [key: string]: unknown };

export type PersonaCreatePayloadMediaPrefs = PersonaCreatePayloadMediaPrefsAnyOf | null;

export type PersonaCreatePayloadPostingWindowsAnyOfItem = { [key: string]: unknown };

export type PersonaCreatePayloadPostingWindows = PersonaCreatePayloadPostingWindowsAnyOfItem[] | null;

export type PersonaCreatePayloadExtrasAnyOf = { [key: string]: unknown };

export type PersonaCreatePayloadExtras = PersonaCreatePayloadExtrasAnyOf | null;

export interface PersonaCreatePayload {
  /** @maxLength 100 */
  name: string;
  /**
   * @maxLength 512
   * @nullable
   */
  avatar_url?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  bio?: string | null;
  /** @maxLength 10 */
  language?: string;
  /**
   * @maxLength 40
   * @nullable
   */
  tone?: string | null;
  /** @nullable */
  style_guide?: string | null;
  pillars?: PersonaCreatePayloadPillars;
  banned_words?: PersonaCreatePayloadBannedWords;
  default_hashtags?: PersonaCreatePayloadDefaultHashtags;
  hashtag_rules?: PersonaCreatePayloadHashtagRules;
  link_policy?: PersonaCreatePayloadLinkPolicy;
  media_prefs?: PersonaCreatePayloadMediaPrefs;
  posting_windows?: PersonaCreatePayloadPostingWindows;
  extras?: PersonaCreatePayloadExtras;
  schema_version?: number;
}

export type PersonaDeleteCommandPersonaId = number | null;

export interface PersonaDeleteCommand {
  persona_id?: PersonaDeleteCommandPersonaId;
}

export type PersonaOutPillars = string[] | null;

export type PersonaOutBannedWords = string[] | null;

export type PersonaOutDefaultHashtags = string[] | null;

export type PersonaOutHashtagRulesAnyOf = { [key: string]: unknown };

export type PersonaOutHashtagRules = PersonaOutHashtagRulesAnyOf | null;

export type PersonaOutLinkPolicyAnyOf = { [key: string]: unknown };

export type PersonaOutLinkPolicy = PersonaOutLinkPolicyAnyOf | null;

export type PersonaOutMediaPrefsAnyOf = { [key: string]: unknown };

export type PersonaOutMediaPrefs = PersonaOutMediaPrefsAnyOf | null;

export type PersonaOutPostingWindowsAnyOfItem = { [key: string]: unknown };

export type PersonaOutPostingWindows = PersonaOutPostingWindowsAnyOfItem[] | null;

export type PersonaOutExtrasAnyOf = { [key: string]: unknown };

export type PersonaOutExtras = PersonaOutExtrasAnyOf | null;

export interface PersonaOut {
  /** @maxLength 100 */
  name: string;
  /**
   * @maxLength 512
   * @nullable
   */
  avatar_url?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  bio?: string | null;
  /** @maxLength 10 */
  language?: string;
  /**
   * @maxLength 40
   * @nullable
   */
  tone?: string | null;
  /** @nullable */
  style_guide?: string | null;
  pillars?: PersonaOutPillars;
  banned_words?: PersonaOutBannedWords;
  default_hashtags?: PersonaOutDefaultHashtags;
  hashtag_rules?: PersonaOutHashtagRules;
  link_policy?: PersonaOutLinkPolicy;
  media_prefs?: PersonaOutMediaPrefs;
  posting_windows?: PersonaOutPostingWindows;
  extras?: PersonaOutExtras;
  schema_version?: number;
  id: number;
  created_at: string;
  updated_at: string;
}

export type PersonaUpdatePillars = string[] | null;

export type PersonaUpdateBannedWords = string[] | null;

export type PersonaUpdateDefaultHashtags = string[] | null;

export type PersonaUpdateHashtagRulesAnyOf = { [key: string]: unknown };

export type PersonaUpdateHashtagRules = PersonaUpdateHashtagRulesAnyOf | null;

export type PersonaUpdateLinkPolicyAnyOf = { [key: string]: unknown };

export type PersonaUpdateLinkPolicy = PersonaUpdateLinkPolicyAnyOf | null;

export type PersonaUpdateMediaPrefsAnyOf = { [key: string]: unknown };

export type PersonaUpdateMediaPrefs = PersonaUpdateMediaPrefsAnyOf | null;

export type PersonaUpdatePostingWindowsAnyOfItem = { [key: string]: unknown };

export type PersonaUpdatePostingWindows = PersonaUpdatePostingWindowsAnyOfItem[] | null;

export type PersonaUpdateExtrasAnyOf = { [key: string]: unknown };

export type PersonaUpdateExtras = PersonaUpdateExtrasAnyOf | null;

export type PersonaUpdateSchemaVersion = number | null;

export interface PersonaUpdate {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  language?: string | null;
  /** @nullable */
  tone?: string | null;
  /** @nullable */
  style_guide?: string | null;
  pillars?: PersonaUpdatePillars;
  banned_words?: PersonaUpdateBannedWords;
  default_hashtags?: PersonaUpdateDefaultHashtags;
  hashtag_rules?: PersonaUpdateHashtagRules;
  link_policy?: PersonaUpdateLinkPolicy;
  media_prefs?: PersonaUpdateMediaPrefs;
  posting_windows?: PersonaUpdatePostingWindows;
  extras?: PersonaUpdateExtras;
  schema_version?: PersonaUpdateSchemaVersion;
}

export type PersonaUpdateCommandPersonaId = number | null;

export interface PersonaUpdateCommand {
  persona_id?: PersonaUpdateCommandPersonaId;
  data: PersonaUpdate;
}

export type PlatformAccountCreateScopes = string[] | null;

export type PlatformAccountCreateIsActive = boolean | null;

export interface PlatformAccountCreate {
  platform: PlatformKind;
  /** @maxLength 128 */
  handle: string;
  /**
   * @maxLength 256
   * @nullable
   */
  external_id?: string | null;
  /**
   * @maxLength 512
   * @nullable
   */
  avatar_url?: string | null;
  /**
   * @maxLength 160
   * @nullable
   */
  bio?: string | null;
  scopes?: PlatformAccountCreateScopes;
  is_active?: PlatformAccountCreateIsActive;
  /** @nullable */
  access_token?: string | null;
  /** @nullable */
  refresh_token?: string | null;
  /** @nullable */
  token_expires_at?: string | null;
}

export interface PlatformAccountCreateCommand {
  account: PlatformAccountCreate;
}

export type PlatformAccountDeleteCommandAccountId = number | null;

export interface PlatformAccountDeleteCommand {
  account_id?: PlatformAccountDeleteCommandAccountId;
  soft?: boolean;
}

export type PlatformAccountOutScopes = string[] | null;

export type PlatformAccountOutIsActive = boolean | null;

export interface PlatformAccountOut {
  platform: PlatformKind;
  /** @maxLength 128 */
  handle: string;
  /**
   * @maxLength 256
   * @nullable
   */
  external_id?: string | null;
  /**
   * @maxLength 512
   * @nullable
   */
  avatar_url?: string | null;
  /**
   * @maxLength 160
   * @nullable
   */
  bio?: string | null;
  scopes?: PlatformAccountOutScopes;
  is_active?: PlatformAccountOutIsActive;
  id: number;
  owner_user_id: number;
  /** @nullable */
  last_checked_at?: string | null;
  /** @nullable */
  last_error?: string | null;
  created_at: string;
  updated_at: string;
}

export type PlatformAccountUpdateScopes = string[] | null;

export type PlatformAccountUpdateIsActive = boolean | null;

export interface PlatformAccountUpdate {
  /** @nullable */
  handle?: string | null;
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  bio?: string | null;
  scopes?: PlatformAccountUpdateScopes;
  is_active?: PlatformAccountUpdateIsActive;
  /** @nullable */
  access_token?: string | null;
  /** @nullable */
  refresh_token?: string | null;
  /** @nullable */
  token_expires_at?: string | null;
}

export type PlatformAccountUpdateCommandAccountId = number | null;

export interface PlatformAccountUpdateCommand {
  account_id?: PlatformAccountUpdateCommandAccountId;
  data: PlatformAccountUpdate;
}

export type PlatformKind = typeof PlatformKind[keyof typeof PlatformKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlatformKind = {
  instagram: 'instagram',
  threads: 'threads',
  x: 'x',
  blog: 'blog',
} as const;

export interface SignupRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  /** @nullable */
  display_name?: string | null;
}

export interface TokenResponse {
  access_token: string;
  token_type?: string;
  user: UserResponse;
}

export interface UserResponse {
  id: number;
  email: string;
  /** @nullable */
  display_name?: string | null;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody = CampaignDeleteCommand | null;

export type AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody = PlatformAccountDeleteCommand | null;

export type AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody = PersonaDeleteCommand | null;

export type AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody = PersonaAccountUnlinkCommand | null;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Signup
 */
export const signupApiOrchestratorAuthSignupPost = (
    signupRequest: SignupRequest,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<UserResponse>(
      {url: `/api/orchestrator/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest, signal
    },
      options);
    }
  


export const getSignupApiOrchestratorAuthSignupPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupApiOrchestratorAuthSignupPost>>, TError,{data: SignupRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof signupApiOrchestratorAuthSignupPost>>, TError,{data: SignupRequest}, TContext> => {

const mutationKey = ['signupApiOrchestratorAuthSignupPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signupApiOrchestratorAuthSignupPost>>, {data: SignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  signupApiOrchestratorAuthSignupPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignupApiOrchestratorAuthSignupPostMutationResult = NonNullable<Awaited<ReturnType<typeof signupApiOrchestratorAuthSignupPost>>>
    export type SignupApiOrchestratorAuthSignupPostMutationBody = SignupRequest
    export type SignupApiOrchestratorAuthSignupPostMutationError = HTTPValidationError

    /**
 * @summary Signup
 */
export const useSignupApiOrchestratorAuthSignupPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupApiOrchestratorAuthSignupPost>>, TError,{data: SignupRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signupApiOrchestratorAuthSignupPost>>,
        TError,
        {data: SignupRequest},
        TContext
      > => {

      const mutationOptions = getSignupApiOrchestratorAuthSignupPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Login
 */
export const loginApiOrchestratorAuthLoginPost = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<TokenResponse>(
      {url: `/api/orchestrator/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getLoginApiOrchestratorAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiOrchestratorAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof loginApiOrchestratorAuthLoginPost>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginApiOrchestratorAuthLoginPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginApiOrchestratorAuthLoginPost>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginApiOrchestratorAuthLoginPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginApiOrchestratorAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginApiOrchestratorAuthLoginPost>>>
    export type LoginApiOrchestratorAuthLoginPostMutationBody = LoginRequest
    export type LoginApiOrchestratorAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginApiOrchestratorAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiOrchestratorAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginApiOrchestratorAuthLoginPost>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginApiOrchestratorAuthLoginPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Create Campaign
 */
export const campaignsCreateCampaignApiOrchestratorCampaignsPost = (
    campaignCreate: CampaignCreate,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<CampaignOut>(
      {url: `/api/orchestrator/campaigns`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: campaignCreate, signal
    },
      options);
    }
  


export const getCampaignsCreateCampaignApiOrchestratorCampaignsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsCreateCampaignApiOrchestratorCampaignsPost>>, TError,{data: CampaignCreate}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignsCreateCampaignApiOrchestratorCampaignsPost>>, TError,{data: CampaignCreate}, TContext> => {

const mutationKey = ['campaignsCreateCampaignApiOrchestratorCampaignsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignsCreateCampaignApiOrchestratorCampaignsPost>>, {data: CampaignCreate}> = (props) => {
          const {data} = props ?? {};

          return  campaignsCreateCampaignApiOrchestratorCampaignsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignsCreateCampaignApiOrchestratorCampaignsPostMutationResult = NonNullable<Awaited<ReturnType<typeof campaignsCreateCampaignApiOrchestratorCampaignsPost>>>
    export type CampaignsCreateCampaignApiOrchestratorCampaignsPostMutationBody = CampaignCreate
    export type CampaignsCreateCampaignApiOrchestratorCampaignsPostMutationError = HTTPValidationError

    /**
 * @summary Create Campaign
 */
export const useCampaignsCreateCampaignApiOrchestratorCampaignsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsCreateCampaignApiOrchestratorCampaignsPost>>, TError,{data: CampaignCreate}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignsCreateCampaignApiOrchestratorCampaignsPost>>,
        TError,
        {data: CampaignCreate},
        TContext
      > => {

      const mutationOptions = getCampaignsCreateCampaignApiOrchestratorCampaignsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Update Campaign
 */
export const campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut = (
    campaignId: number | null,
    campaignUpdateCommand: CampaignUpdateCommand,
 options?: SecondParameter<typeof apiFetch>,) => {
      
      
      return apiFetch<CampaignOut>(
      {url: `/api/orchestrator/campaigns/${campaignId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: campaignUpdateCommand
    },
      options);
    }
  


export const getCampaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut>>, TError,{campaignId: number | null;data: CampaignUpdateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut>>, TError,{campaignId: number | null;data: CampaignUpdateCommand}, TContext> => {

const mutationKey = ['campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut>>, {campaignId: number | null;data: CampaignUpdateCommand}> = (props) => {
          const {campaignId,data} = props ?? {};

          return  campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut(campaignId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut>>>
    export type CampaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutMutationBody = CampaignUpdateCommand
    export type CampaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Campaign
 */
export const useCampaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut>>, TError,{campaignId: number | null;data: CampaignUpdateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPut>>,
        TError,
        {campaignId: number | null;data: CampaignUpdateCommand},
        TContext
      > => {

      const mutationOptions = getCampaignsUpdateCampaignApiOrchestratorCampaignsCampaignIdPutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Delete Campaign
 */
export const campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete = (
    campaignId: number | null,
    campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody: CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody,
 options?: SecondParameter<typeof apiFetch>,) => {
      
      
      return apiFetch<MessageOut>(
      {url: `/api/orchestrator/campaigns/${campaignId}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody
    },
      options);
    }
  


export const getCampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete>>, TError,{campaignId: number | null;data: CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete>>, TError,{campaignId: number | null;data: CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody}, TContext> => {

const mutationKey = ['campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete>>, {campaignId: number | null;data: CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody}> = (props) => {
          const {campaignId,data} = props ?? {};

          return  campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete(campaignId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete>>>
    export type CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteMutationBody = CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody
    export type CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Campaign
 */
export const useCampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete>>, TError,{campaignId: number | null;data: CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDelete>>,
        TError,
        {campaignId: number | null;data: CampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteBody},
        TContext
      > => {

      const mutationOptions = getCampaignsDeleteCampaignApiOrchestratorCampaignsCampaignIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Upsert KPI Definitions
 */
export const campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut = (
    campaignId: number | null,
    campaignKPIDefUpsertCommand: CampaignKPIDefUpsertCommand,
 options?: SecondParameter<typeof apiFetch>,) => {
      
      
      return apiFetch<CampaignKPIDefListOut>(
      {url: `/api/orchestrator/campaigns/${campaignId}/kpi-defs`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: campaignKPIDefUpsertCommand
    },
      options);
    }
  


export const getCampaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut>>, TError,{campaignId: number | null;data: CampaignKPIDefUpsertCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut>>, TError,{campaignId: number | null;data: CampaignKPIDefUpsertCommand}, TContext> => {

const mutationKey = ['campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut>>, {campaignId: number | null;data: CampaignKPIDefUpsertCommand}> = (props) => {
          const {campaignId,data} = props ?? {};

          return  campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut(campaignId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutMutationResult = NonNullable<Awaited<ReturnType<typeof campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut>>>
    export type CampaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutMutationBody = CampaignKPIDefUpsertCommand
    export type CampaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutMutationError = HTTPValidationError

    /**
 * @summary Upsert KPI Definitions
 */
export const useCampaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut>>, TError,{campaignId: number | null;data: CampaignKPIDefUpsertCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPut>>,
        TError,
        {campaignId: number | null;data: CampaignKPIDefUpsertCommand},
        TContext
      > => {

      const mutationOptions = getCampaignsUpsertKpiDefsApiOrchestratorCampaignsCampaignIdKpiDefsPutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Record KPI Result
 */
export const campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost = (
    campaignId: number | null,
    campaignKPIRecordCommand: CampaignKPIRecordCommand,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<CampaignKPIResultOut>(
      {url: `/api/orchestrator/campaigns/${campaignId}/kpi-results`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: campaignKPIRecordCommand, signal
    },
      options);
    }
  


export const getCampaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost>>, TError,{campaignId: number | null;data: CampaignKPIRecordCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost>>, TError,{campaignId: number | null;data: CampaignKPIRecordCommand}, TContext> => {

const mutationKey = ['campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost>>, {campaignId: number | null;data: CampaignKPIRecordCommand}> = (props) => {
          const {campaignId,data} = props ?? {};

          return  campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost(campaignId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPostMutationResult = NonNullable<Awaited<ReturnType<typeof campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost>>>
    export type CampaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPostMutationBody = CampaignKPIRecordCommand
    export type CampaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPostMutationError = HTTPValidationError

    /**
 * @summary Record KPI Result
 */
export const useCampaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost>>, TError,{campaignId: number | null;data: CampaignKPIRecordCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPost>>,
        TError,
        {campaignId: number | null;data: CampaignKPIRecordCommand},
        TContext
      > => {

      const mutationOptions = getCampaignsRecordKpiResultApiOrchestratorCampaignsCampaignIdKpiResultsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Aggregate KPI
 */
export const campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost = (
    campaignId: number | null,
    campaignAggregationCommand: CampaignAggregationCommand,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<CampaignKPIResultOut>(
      {url: `/api/orchestrator/campaigns/${campaignId}/aggregate-kpis`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: campaignAggregationCommand, signal
    },
      options);
    }
  


export const getCampaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost>>, TError,{campaignId: number | null;data: CampaignAggregationCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost>>, TError,{campaignId: number | null;data: CampaignAggregationCommand}, TContext> => {

const mutationKey = ['campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost>>, {campaignId: number | null;data: CampaignAggregationCommand}> = (props) => {
          const {campaignId,data} = props ?? {};

          return  campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost(campaignId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPostMutationResult = NonNullable<Awaited<ReturnType<typeof campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost>>>
    export type CampaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPostMutationBody = CampaignAggregationCommand
    export type CampaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPostMutationError = HTTPValidationError

    /**
 * @summary Aggregate KPI
 */
export const useCampaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost>>, TError,{campaignId: number | null;data: CampaignAggregationCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPost>>,
        TError,
        {campaignId: number | null;data: CampaignAggregationCommand},
        TContext
      > => {

      const mutationOptions = getCampaignsAggregateKpisApiOrchestratorCampaignsCampaignIdAggregateKpisPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Create Draft
 */
export const draftsCreateApiOrchestratorDraftsPost = (
    draftSaveRequest: DraftSaveRequest,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<DraftOut>(
      {url: `/api/orchestrator/drafts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: draftSaveRequest, signal
    },
      options);
    }
  


export const getDraftsCreateApiOrchestratorDraftsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsCreateApiOrchestratorDraftsPost>>, TError,{data: DraftSaveRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof draftsCreateApiOrchestratorDraftsPost>>, TError,{data: DraftSaveRequest}, TContext> => {

const mutationKey = ['draftsCreateApiOrchestratorDraftsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof draftsCreateApiOrchestratorDraftsPost>>, {data: DraftSaveRequest}> = (props) => {
          const {data} = props ?? {};

          return  draftsCreateApiOrchestratorDraftsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DraftsCreateApiOrchestratorDraftsPostMutationResult = NonNullable<Awaited<ReturnType<typeof draftsCreateApiOrchestratorDraftsPost>>>
    export type DraftsCreateApiOrchestratorDraftsPostMutationBody = DraftSaveRequest
    export type DraftsCreateApiOrchestratorDraftsPostMutationError = HTTPValidationError

    /**
 * @summary Create Draft
 */
export const useDraftsCreateApiOrchestratorDraftsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsCreateApiOrchestratorDraftsPost>>, TError,{data: DraftSaveRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof draftsCreateApiOrchestratorDraftsPost>>,
        TError,
        {data: DraftSaveRequest},
        TContext
      > => {

      const mutationOptions = getDraftsCreateApiOrchestratorDraftsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Update Draft
 */
export const draftsUpdateIrApiOrchestratorDraftsDraftIdIrPut = (
    draftId: number | null,
    draftUpdateCommand: DraftUpdateCommand,
 options?: SecondParameter<typeof apiFetch>,) => {
      
      
      return apiFetch<DraftOut>(
      {url: `/api/orchestrator/drafts/${draftId}/ir`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: draftUpdateCommand
    },
      options);
    }
  


export const getDraftsUpdateIrApiOrchestratorDraftsDraftIdIrPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsUpdateIrApiOrchestratorDraftsDraftIdIrPut>>, TError,{draftId: number | null;data: DraftUpdateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof draftsUpdateIrApiOrchestratorDraftsDraftIdIrPut>>, TError,{draftId: number | null;data: DraftUpdateCommand}, TContext> => {

const mutationKey = ['draftsUpdateIrApiOrchestratorDraftsDraftIdIrPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof draftsUpdateIrApiOrchestratorDraftsDraftIdIrPut>>, {draftId: number | null;data: DraftUpdateCommand}> = (props) => {
          const {draftId,data} = props ?? {};

          return  draftsUpdateIrApiOrchestratorDraftsDraftIdIrPut(draftId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DraftsUpdateIrApiOrchestratorDraftsDraftIdIrPutMutationResult = NonNullable<Awaited<ReturnType<typeof draftsUpdateIrApiOrchestratorDraftsDraftIdIrPut>>>
    export type DraftsUpdateIrApiOrchestratorDraftsDraftIdIrPutMutationBody = DraftUpdateCommand
    export type DraftsUpdateIrApiOrchestratorDraftsDraftIdIrPutMutationError = HTTPValidationError

    /**
 * @summary Update Draft
 */
export const useDraftsUpdateIrApiOrchestratorDraftsDraftIdIrPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsUpdateIrApiOrchestratorDraftsDraftIdIrPut>>, TError,{draftId: number | null;data: DraftUpdateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof draftsUpdateIrApiOrchestratorDraftsDraftIdIrPut>>,
        TError,
        {draftId: number | null;data: DraftUpdateCommand},
        TContext
      > => {

      const mutationOptions = getDraftsUpdateIrApiOrchestratorDraftsDraftIdIrPutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Create Platform Account
 */
export const accountsPlatformCreateApiOrchestratorAccountsPlatformPost = (
    platformAccountCreateCommand: PlatformAccountCreateCommand,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<PlatformAccountOut>(
      {url: `/api/orchestrator/accounts/platform`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: platformAccountCreateCommand, signal
    },
      options);
    }
  


export const getAccountsPlatformCreateApiOrchestratorAccountsPlatformPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPlatformCreateApiOrchestratorAccountsPlatformPost>>, TError,{data: PlatformAccountCreateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof accountsPlatformCreateApiOrchestratorAccountsPlatformPost>>, TError,{data: PlatformAccountCreateCommand}, TContext> => {

const mutationKey = ['accountsPlatformCreateApiOrchestratorAccountsPlatformPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountsPlatformCreateApiOrchestratorAccountsPlatformPost>>, {data: PlatformAccountCreateCommand}> = (props) => {
          const {data} = props ?? {};

          return  accountsPlatformCreateApiOrchestratorAccountsPlatformPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AccountsPlatformCreateApiOrchestratorAccountsPlatformPostMutationResult = NonNullable<Awaited<ReturnType<typeof accountsPlatformCreateApiOrchestratorAccountsPlatformPost>>>
    export type AccountsPlatformCreateApiOrchestratorAccountsPlatformPostMutationBody = PlatformAccountCreateCommand
    export type AccountsPlatformCreateApiOrchestratorAccountsPlatformPostMutationError = HTTPValidationError

    /**
 * @summary Create Platform Account
 */
export const useAccountsPlatformCreateApiOrchestratorAccountsPlatformPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPlatformCreateApiOrchestratorAccountsPlatformPost>>, TError,{data: PlatformAccountCreateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountsPlatformCreateApiOrchestratorAccountsPlatformPost>>,
        TError,
        {data: PlatformAccountCreateCommand},
        TContext
      > => {

      const mutationOptions = getAccountsPlatformCreateApiOrchestratorAccountsPlatformPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Update Platform Account
 */
export const accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut = (
    accountId: number | null,
    platformAccountUpdateCommand: PlatformAccountUpdateCommand,
 options?: SecondParameter<typeof apiFetch>,) => {
      
      
      return apiFetch<PlatformAccountOut>(
      {url: `/api/orchestrator/accounts/platform/${accountId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: platformAccountUpdateCommand
    },
      options);
    }
  


export const getAccountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut>>, TError,{accountId: number | null;data: PlatformAccountUpdateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut>>, TError,{accountId: number | null;data: PlatformAccountUpdateCommand}, TContext> => {

const mutationKey = ['accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut>>, {accountId: number | null;data: PlatformAccountUpdateCommand}> = (props) => {
          const {accountId,data} = props ?? {};

          return  accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut(accountId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AccountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut>>>
    export type AccountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutMutationBody = PlatformAccountUpdateCommand
    export type AccountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Platform Account
 */
export const useAccountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut>>, TError,{accountId: number | null;data: PlatformAccountUpdateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPut>>,
        TError,
        {accountId: number | null;data: PlatformAccountUpdateCommand},
        TContext
      > => {

      const mutationOptions = getAccountsPlatformUpdateApiOrchestratorAccountsPlatformAccountIdPutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Delete Platform Account
 */
export const accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete = (
    accountId: number | null,
    accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody: AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody,
 options?: SecondParameter<typeof apiFetch>,) => {
      
      
      return apiFetch<MessageOut>(
      {url: `/api/orchestrator/accounts/platform/${accountId}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody
    },
      options);
    }
  


export const getAccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete>>, TError,{accountId: number | null;data: AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete>>, TError,{accountId: number | null;data: AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody}, TContext> => {

const mutationKey = ['accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete>>, {accountId: number | null;data: AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody}> = (props) => {
          const {accountId,data} = props ?? {};

          return  accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete(accountId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete>>>
    export type AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteMutationBody = AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody
    export type AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Platform Account
 */
export const useAccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete>>, TError,{accountId: number | null;data: AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDelete>>,
        TError,
        {accountId: number | null;data: AccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteBody},
        TContext
      > => {

      const mutationOptions = getAccountsPlatformDeleteApiOrchestratorAccountsPlatformAccountIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Create Persona
 */
export const accountsPersonaCreateApiOrchestratorAccountsPersonasPost = (
    personaCreateCommand: PersonaCreateCommand,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<PersonaOut>(
      {url: `/api/orchestrator/accounts/personas`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: personaCreateCommand, signal
    },
      options);
    }
  


export const getAccountsPersonaCreateApiOrchestratorAccountsPersonasPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPersonaCreateApiOrchestratorAccountsPersonasPost>>, TError,{data: PersonaCreateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof accountsPersonaCreateApiOrchestratorAccountsPersonasPost>>, TError,{data: PersonaCreateCommand}, TContext> => {

const mutationKey = ['accountsPersonaCreateApiOrchestratorAccountsPersonasPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountsPersonaCreateApiOrchestratorAccountsPersonasPost>>, {data: PersonaCreateCommand}> = (props) => {
          const {data} = props ?? {};

          return  accountsPersonaCreateApiOrchestratorAccountsPersonasPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AccountsPersonaCreateApiOrchestratorAccountsPersonasPostMutationResult = NonNullable<Awaited<ReturnType<typeof accountsPersonaCreateApiOrchestratorAccountsPersonasPost>>>
    export type AccountsPersonaCreateApiOrchestratorAccountsPersonasPostMutationBody = PersonaCreateCommand
    export type AccountsPersonaCreateApiOrchestratorAccountsPersonasPostMutationError = HTTPValidationError

    /**
 * @summary Create Persona
 */
export const useAccountsPersonaCreateApiOrchestratorAccountsPersonasPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPersonaCreateApiOrchestratorAccountsPersonasPost>>, TError,{data: PersonaCreateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountsPersonaCreateApiOrchestratorAccountsPersonasPost>>,
        TError,
        {data: PersonaCreateCommand},
        TContext
      > => {

      const mutationOptions = getAccountsPersonaCreateApiOrchestratorAccountsPersonasPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Update Persona
 */
export const accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut = (
    personaId: number | null,
    personaUpdateCommand: PersonaUpdateCommand,
 options?: SecondParameter<typeof apiFetch>,) => {
      
      
      return apiFetch<PersonaOut>(
      {url: `/api/orchestrator/accounts/personas/${personaId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: personaUpdateCommand
    },
      options);
    }
  


export const getAccountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut>>, TError,{personaId: number | null;data: PersonaUpdateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut>>, TError,{personaId: number | null;data: PersonaUpdateCommand}, TContext> => {

const mutationKey = ['accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut>>, {personaId: number | null;data: PersonaUpdateCommand}> = (props) => {
          const {personaId,data} = props ?? {};

          return  accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut(personaId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AccountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut>>>
    export type AccountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutMutationBody = PersonaUpdateCommand
    export type AccountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Persona
 */
export const useAccountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut>>, TError,{personaId: number | null;data: PersonaUpdateCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPut>>,
        TError,
        {personaId: number | null;data: PersonaUpdateCommand},
        TContext
      > => {

      const mutationOptions = getAccountsPersonaUpdateApiOrchestratorAccountsPersonasPersonaIdPutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Delete Persona
 */
export const accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete = (
    personaId: number | null,
    accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody: AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody,
 options?: SecondParameter<typeof apiFetch>,) => {
      
      
      return apiFetch<MessageOut>(
      {url: `/api/orchestrator/accounts/personas/${personaId}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody
    },
      options);
    }
  


export const getAccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete>>, TError,{personaId: number | null;data: AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete>>, TError,{personaId: number | null;data: AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody}, TContext> => {

const mutationKey = ['accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete>>, {personaId: number | null;data: AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody}> = (props) => {
          const {personaId,data} = props ?? {};

          return  accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete(personaId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete>>>
    export type AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteMutationBody = AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody
    export type AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Persona
 */
export const useAccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete>>, TError,{personaId: number | null;data: AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDelete>>,
        TError,
        {personaId: number | null;data: AccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteBody},
        TContext
      > => {

      const mutationOptions = getAccountsPersonaDeleteApiOrchestratorAccountsPersonasPersonaIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Link Persona Account
 */
export const accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost = (
    personaAccountLinkCommand: PersonaAccountLinkCommand,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<PersonaAccountOut>(
      {url: `/api/orchestrator/accounts/persona-account-links`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: personaAccountLinkCommand, signal
    },
      options);
    }
  


export const getAccountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost>>, TError,{data: PersonaAccountLinkCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost>>, TError,{data: PersonaAccountLinkCommand}, TContext> => {

const mutationKey = ['accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost>>, {data: PersonaAccountLinkCommand}> = (props) => {
          const {data} = props ?? {};

          return  accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AccountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostMutationResult = NonNullable<Awaited<ReturnType<typeof accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost>>>
    export type AccountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostMutationBody = PersonaAccountLinkCommand
    export type AccountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostMutationError = HTTPValidationError

    /**
 * @summary Link Persona Account
 */
export const useAccountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost>>, TError,{data: PersonaAccountLinkCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPost>>,
        TError,
        {data: PersonaAccountLinkCommand},
        TContext
      > => {

      const mutationOptions = getAccountsLinkCreateApiOrchestratorAccountsPersonaAccountLinksPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Unlink Persona Account
 */
export const accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete = (
    personaId: number | null,
    accountId: number | null,
    accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody: AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody,
 options?: SecondParameter<typeof apiFetch>,) => {
      
      
      return apiFetch<MessageOut>(
      {url: `/api/orchestrator/accounts/persona-account-links/${personaId}/${accountId}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody
    },
      options);
    }
  


export const getAccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete>>, TError,{personaId: number | null;accountId: number | null;data: AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete>>, TError,{personaId: number | null;accountId: number | null;data: AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody}, TContext> => {

const mutationKey = ['accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete>>, {personaId: number | null;accountId: number | null;data: AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody}> = (props) => {
          const {personaId,accountId,data} = props ?? {};

          return  accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete(personaId,accountId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete>>>
    export type AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteMutationBody = AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody
    export type AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Unlink Persona Account
 */
export const useAccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete>>, TError,{personaId: number | null;accountId: number | null;data: AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDelete>>,
        TError,
        {personaId: number | null;accountId: number | null;data: AccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteBody},
        TContext
      > => {

      const mutationOptions = getAccountsLinkDeleteApiOrchestratorAccountsPersonaAccountLinksPersonaIdAccountIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Ingest Insight
 */
export const insightsIngestApiOrchestratorInsightsPost = (
    insightInCommand: InsightInCommand,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<InsightOut>(
      {url: `/api/orchestrator/insights`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: insightInCommand, signal
    },
      options);
    }
  


export const getInsightsIngestApiOrchestratorInsightsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insightsIngestApiOrchestratorInsightsPost>>, TError,{data: InsightInCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof insightsIngestApiOrchestratorInsightsPost>>, TError,{data: InsightInCommand}, TContext> => {

const mutationKey = ['insightsIngestApiOrchestratorInsightsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof insightsIngestApiOrchestratorInsightsPost>>, {data: InsightInCommand}> = (props) => {
          const {data} = props ?? {};

          return  insightsIngestApiOrchestratorInsightsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InsightsIngestApiOrchestratorInsightsPostMutationResult = NonNullable<Awaited<ReturnType<typeof insightsIngestApiOrchestratorInsightsPost>>>
    export type InsightsIngestApiOrchestratorInsightsPostMutationBody = InsightInCommand
    export type InsightsIngestApiOrchestratorInsightsPostMutationError = HTTPValidationError

    /**
 * @summary Ingest Insight
 */
export const useInsightsIngestApiOrchestratorInsightsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insightsIngestApiOrchestratorInsightsPost>>, TError,{data: InsightInCommand}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof insightsIngestApiOrchestratorInsightsPost>>,
        TError,
        {data: InsightInCommand},
        TContext
      > => {

      const mutationOptions = getInsightsIngestApiOrchestratorInsightsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Chat Query
 */
export const chatQueryApiOrchestratorChatQueryPost = (
    chatQuery: ChatQuery,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<ChatResponse>(
      {url: `/api/orchestrator/chat/query`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chatQuery, signal
    },
      options);
    }
  


export const getChatQueryApiOrchestratorChatQueryPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatQueryApiOrchestratorChatQueryPost>>, TError,{data: ChatQuery}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof chatQueryApiOrchestratorChatQueryPost>>, TError,{data: ChatQuery}, TContext> => {

const mutationKey = ['chatQueryApiOrchestratorChatQueryPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chatQueryApiOrchestratorChatQueryPost>>, {data: ChatQuery}> = (props) => {
          const {data} = props ?? {};

          return  chatQueryApiOrchestratorChatQueryPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChatQueryApiOrchestratorChatQueryPostMutationResult = NonNullable<Awaited<ReturnType<typeof chatQueryApiOrchestratorChatQueryPost>>>
    export type ChatQueryApiOrchestratorChatQueryPostMutationBody = ChatQuery
    export type ChatQueryApiOrchestratorChatQueryPostMutationError = HTTPValidationError

    /**
 * @summary Chat Query
 */
export const useChatQueryApiOrchestratorChatQueryPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatQueryApiOrchestratorChatQueryPost>>, TError,{data: ChatQuery}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chatQueryApiOrchestratorChatQueryPost>>,
        TError,
        {data: ChatQuery},
        TContext
      > => {

      const mutationOptions = getChatQueryApiOrchestratorChatQueryPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Get list of all available flows.
 * @summary Get Available Flows
 */
export const getAvailableFlowsApiOrchestratorChatFlowsGet = (
    
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<FlowInfo[]>(
      {url: `/api/orchestrator/chat/flows`, method: 'GET', signal
    },
      options);
    }
  

export const getGetAvailableFlowsApiOrchestratorChatFlowsGetQueryKey = () => {
    return [`/api/orchestrator/chat/flows`] as const;
    }

    
export const getGetAvailableFlowsApiOrchestratorChatFlowsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAvailableFlowsApiOrchestratorChatFlowsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>> = ({ signal }) => getAvailableFlowsApiOrchestratorChatFlowsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAvailableFlowsApiOrchestratorChatFlowsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>>
export type GetAvailableFlowsApiOrchestratorChatFlowsGetQueryError = unknown


export function useGetAvailableFlowsApiOrchestratorChatFlowsGet<TData = Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>,
          TError,
          Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailableFlowsApiOrchestratorChatFlowsGet<TData = Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>,
          TError,
          Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailableFlowsApiOrchestratorChatFlowsGet<TData = Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Available Flows
 */

export function useGetAvailableFlowsApiOrchestratorChatFlowsGet<TData = Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableFlowsApiOrchestratorChatFlowsGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAvailableFlowsApiOrchestratorChatFlowsGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Health
 */
export const healthApiHealthGet = (
    
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<unknown>(
      {url: `/api/health`, method: 'GET', signal
    },
      options);
    }
  

export const getHealthApiHealthGetQueryKey = () => {
    return [`/api/health`] as const;
    }

    
export const getHealthApiHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthApiHealthGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthApiHealthGet>>> = ({ signal }) => healthApiHealthGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthApiHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthApiHealthGet>>>
export type HealthApiHealthGetQueryError = unknown


export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthApiHealthGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
