/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Maestro Backend
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiFetch } from './fetcher';
export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LoginRequest {
  email: string;
  password: string;
}

export type NewsItemNewsItemTitle = string | null;

export type NewsItemNewsItemUrl = string | null;

export type NewsItemNewsItemPicture = string | null;

export type NewsItemNewsItemSource = string | null;

/**
 * 개별 뉴스 아이템 스키마
 */
export interface NewsItem {
  news_item_title?: NewsItemNewsItemTitle;
  news_item_url?: NewsItemNewsItemUrl;
  news_item_picture?: NewsItemNewsItemPicture;
  news_item_source?: NewsItemNewsItemSource;
}

export type SignupRequestDisplayName = string | null;

export interface SignupRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  display_name?: SignupRequestDisplayName;
}

export interface TokenResponse {
  access_token: string;
  token_type?: string;
  user: UserResponse;
}

/**
 * 데이터 수집 시각 (ISO format)
 */
export type TrendItemRetrieved = string | string;

/**
 * 대략적인 트래픽 (예: '200+', '1000+')
 */
export type TrendItemApproxTraffic = string | null;

/**
 * Google Trends 링크
 */
export type TrendItemLink = string | null;

/**
 * 발행 날짜
 */
export type TrendItemPubDate = string | null;

/**
 * 대표 이미지 URL
 */
export type TrendItemPicture = string | null;

/**
 * 이미지 출처
 */
export type TrendItemPictureSource = string | null;

/**
 * 뉴스 아이템 (보통 빈 문자열)
 */
export type TrendItemNewsItem = string | null;

/**
 * 관련 뉴스 아이템 목록
 */
export type TrendItemNewsItems = NewsItem[] | null;

/**
 * Google Trends 개별 트렌드 아이템 스키마
 */
export interface TrendItem {
  /** 트렌드 순위 */
  rank: number;
  /** 데이터 수집 시각 (ISO format) */
  retrieved: TrendItemRetrieved;
  /** 트렌드 키워드 */
  title: string;
  /** 대략적인 트래픽 (예: '200+', '1000+') */
  approx_traffic?: TrendItemApproxTraffic;
  /** Google Trends 링크 */
  link?: TrendItemLink;
  /** 발행 날짜 */
  pubDate?: TrendItemPubDate;
  /** 대표 이미지 URL */
  picture?: TrendItemPicture;
  /** 이미지 출처 */
  picture_source?: TrendItemPictureSource;
  /** 뉴스 아이템 (보통 빈 문자열) */
  news_item?: TrendItemNewsItem;
  /** 관련 뉴스 아이템 목록 */
  news_items?: TrendItemNewsItems;
  [key: string]: unknown;
 }

/**
 * 데이터 소스 (예: cache, db, vector)
 */
export type TrendsListResponseSource = typeof TrendsListResponseSource[keyof typeof TrendsListResponseSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrendsListResponseSource = {
  cache: 'cache',
  db: 'db',
  vector: 'vector',
} as const;

/**
 * 키워드 (있으면 벡터 유사검색)
 */
export type TrendsListResponseQuery = string | null;

export interface TrendsListResponse {
  /** 국가 코드 (예: KR, US) */
  country: string;
  /** 데이터 소스 (예: cache, db, vector) */
  source: TrendsListResponseSource;
  /** 키워드 (있으면 벡터 유사검색) */
  query?: TrendsListResponseQuery;
  /** 트렌드 아이템 목록 */
  items: TrendItem[];
}

export type UserResponseDisplayName = string | null;

export interface UserResponse {
  id: number;
  email: string;
  display_name?: UserResponseDisplayName;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type ListTrendsApiTrendsGetParams = {
country?: string;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * 검색 질의(벡터검색)
 */
q?: string | null;
/**
 * YYYY-MM-DD (단일 일자)
 */
on_date?: string | null;
/**
 * YYYY-MM-DD (이후/포함)
 */
since?: string | null;
/**
 * YYYY-MM-DD (이전/포함)
 */
until?: string | null;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Trends
 */
export const listTrendsApiTrendsGet = (
    params?: ListTrendsApiTrendsGetParams,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<TrendsListResponse>(
      {url: `/api/trends`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getListTrendsApiTrendsGetQueryKey = (params?: ListTrendsApiTrendsGetParams,) => {
    return [`/api/trends`, ...(params ? [params]: [])] as const;
    }

    
export const getListTrendsApiTrendsGetQueryOptions = <TData = Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError = HTTPValidationError>(params?: ListTrendsApiTrendsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTrendsApiTrendsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTrendsApiTrendsGet>>> = ({ signal }) => listTrendsApiTrendsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTrendsApiTrendsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTrendsApiTrendsGet>>>
export type ListTrendsApiTrendsGetQueryError = HTTPValidationError


export function useListTrendsApiTrendsGet<TData = Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListTrendsApiTrendsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTrendsApiTrendsGet>>,
          TError,
          Awaited<ReturnType<typeof listTrendsApiTrendsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTrendsApiTrendsGet<TData = Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError = HTTPValidationError>(
 params?: ListTrendsApiTrendsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTrendsApiTrendsGet>>,
          TError,
          Awaited<ReturnType<typeof listTrendsApiTrendsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTrendsApiTrendsGet<TData = Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError = HTTPValidationError>(
 params?: ListTrendsApiTrendsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Trends
 */

export function useListTrendsApiTrendsGet<TData = Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError = HTTPValidationError>(
 params?: ListTrendsApiTrendsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrendsApiTrendsGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTrendsApiTrendsGetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Signup
 */
export const signupApiAuthSignupPost = (
    signupRequest: SignupRequest,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<UserResponse>(
      {url: `/api/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest, signal
    },
      options);
    }
  


export const getSignupApiAuthSignupPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, TError,{data: SignupRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, TError,{data: SignupRequest}, TContext> => {

const mutationKey = ['signupApiAuthSignupPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, {data: SignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  signupApiAuthSignupPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignupApiAuthSignupPostMutationResult = NonNullable<Awaited<ReturnType<typeof signupApiAuthSignupPost>>>
    export type SignupApiAuthSignupPostMutationBody = SignupRequest
    export type SignupApiAuthSignupPostMutationError = HTTPValidationError

    /**
 * @summary Signup
 */
export const useSignupApiAuthSignupPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, TError,{data: SignupRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signupApiAuthSignupPost>>,
        TError,
        {data: SignupRequest},
        TContext
      > => {

      const mutationOptions = getSignupApiAuthSignupPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Login
 */
export const loginApiAuthLoginPost = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<TokenResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getLoginApiAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginApiAuthLoginPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginApiAuthLoginPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginApiAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginApiAuthLoginPost>>>
    export type LoginApiAuthLoginPostMutationBody = LoginRequest
    export type LoginApiAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginApiAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginApiAuthLoginPost>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginApiAuthLoginPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Me
 */
export const meApiMeGet = (
    
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<UserResponse>(
      {url: `/api/me`, method: 'GET', signal
    },
      options);
    }
  

export const getMeApiMeGetQueryKey = () => {
    return [`/api/me`] as const;
    }

    
export const getMeApiMeGetQueryOptions = <TData = Awaited<ReturnType<typeof meApiMeGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiMeGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeApiMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof meApiMeGet>>> = ({ signal }) => meApiMeGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof meApiMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeApiMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof meApiMeGet>>>
export type MeApiMeGetQueryError = unknown


export function useMeApiMeGet<TData = Awaited<ReturnType<typeof meApiMeGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meApiMeGet>>,
          TError,
          Awaited<ReturnType<typeof meApiMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeApiMeGet<TData = Awaited<ReturnType<typeof meApiMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meApiMeGet>>,
          TError,
          Awaited<ReturnType<typeof meApiMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeApiMeGet<TData = Awaited<ReturnType<typeof meApiMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiMeGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Me
 */

export function useMeApiMeGet<TData = Awaited<ReturnType<typeof meApiMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiMeGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeApiMeGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Health
 */
export const healthApiHealthGet = (
    
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<unknown>(
      {url: `/api/health`, method: 'GET', signal
    },
      options);
    }
  

export const getHealthApiHealthGetQueryKey = () => {
    return [`/api/health`] as const;
    }

    
export const getHealthApiHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthApiHealthGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthApiHealthGet>>> = ({ signal }) => healthApiHealthGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthApiHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthApiHealthGet>>>
export type HealthApiHealthGetQueryError = unknown


export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthApiHealthGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
