/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Maestro Backend
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LoginRequest {
  email: string;
  password: string;
}

export type SignupRequestDisplayName = string | null;

export interface SignupRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  display_name?: SignupRequestDisplayName;
}

export interface TokenResponse {
  access_token: string;
  token_type?: string;
  user: UserResponse;
}

export type UserResponseDisplayName = string | null;

export interface UserResponse {
  id: number;
  email: string;
  display_name?: UserResponseDisplayName;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

/**
 * @summary Signup
 */
export type signupApiAuthSignupPostResponse201 = {
  data: UserResponse
  status: 201
}

export type signupApiAuthSignupPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type signupApiAuthSignupPostResponseComposite = signupApiAuthSignupPostResponse201 | signupApiAuthSignupPostResponse422;
    
export type signupApiAuthSignupPostResponse = signupApiAuthSignupPostResponseComposite & {
  headers: Headers;
}

export const getSignupApiAuthSignupPostUrl = () => {


  

  return `http://localhost:8000/api/auth/signup`
}

export const signupApiAuthSignupPost = async (signupRequest: SignupRequest, options?: RequestInit): Promise<signupApiAuthSignupPostResponse> => {
  
  const res = await fetch(getSignupApiAuthSignupPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: signupApiAuthSignupPostResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as signupApiAuthSignupPostResponse
}




export const getSignupApiAuthSignupPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, TError,{data: SignupRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, TError,{data: SignupRequest}, TContext> => {

const mutationKey = ['signupApiAuthSignupPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, {data: SignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  signupApiAuthSignupPost(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignupApiAuthSignupPostMutationResult = NonNullable<Awaited<ReturnType<typeof signupApiAuthSignupPost>>>
    export type SignupApiAuthSignupPostMutationBody = SignupRequest
    export type SignupApiAuthSignupPostMutationError = HTTPValidationError

    /**
 * @summary Signup
 */
export const useSignupApiAuthSignupPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, TError,{data: SignupRequest}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof signupApiAuthSignupPost>>,
        TError,
        {data: SignupRequest},
        TContext
      > => {

      const mutationOptions = getSignupApiAuthSignupPostMutationOptions(options);

      return useMutation(mutationOptions );
    }
    
/**
 * @summary Login
 */
export type loginApiAuthLoginPostResponse200 = {
  data: TokenResponse
  status: 200
}

export type loginApiAuthLoginPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type loginApiAuthLoginPostResponseComposite = loginApiAuthLoginPostResponse200 | loginApiAuthLoginPostResponse422;
    
export type loginApiAuthLoginPostResponse = loginApiAuthLoginPostResponseComposite & {
  headers: Headers;
}

export const getLoginApiAuthLoginPostUrl = () => {


  

  return `http://localhost:8000/api/auth/login`
}

export const loginApiAuthLoginPost = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginApiAuthLoginPostResponse> => {
  
  const res = await fetch(getLoginApiAuthLoginPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: loginApiAuthLoginPostResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as loginApiAuthLoginPostResponse
}




export const getLoginApiAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginApiAuthLoginPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginApiAuthLoginPost(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginApiAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginApiAuthLoginPost>>>
    export type LoginApiAuthLoginPostMutationBody = LoginRequest
    export type LoginApiAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginApiAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof loginApiAuthLoginPost>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginApiAuthLoginPostMutationOptions(options);

      return useMutation(mutationOptions );
    }
    
/**
 * @summary Me
 */
export type meApiMeGetResponse200 = {
  data: UserResponse
  status: 200
}
    
export type meApiMeGetResponseComposite = meApiMeGetResponse200;
    
export type meApiMeGetResponse = meApiMeGetResponseComposite & {
  headers: Headers;
}

export const getMeApiMeGetUrl = () => {


  

  return `http://localhost:8000/api/me`
}

export const meApiMeGet = async ( options?: RequestInit): Promise<meApiMeGetResponse> => {
  
  const res = await fetch(getMeApiMeGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: meApiMeGetResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as meApiMeGetResponse
}



export const getMeApiMeGetQueryKey = () => {
    return [`http://localhost:8000/api/me`] as const;
    }

    
export const getMeApiMeGetQueryOptions = <TData = Awaited<ReturnType<typeof meApiMeGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof meApiMeGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeApiMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof meApiMeGet>>> = ({ signal }) => meApiMeGet({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof meApiMeGet>>, TError, TData> & { queryKey: QueryKey }
}

export type MeApiMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof meApiMeGet>>>
export type MeApiMeGetQueryError = unknown


/**
 * @summary Me
 */

export function useMeApiMeGet<TData = Awaited<ReturnType<typeof meApiMeGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof meApiMeGet>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getMeApiMeGetQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Health
 */
export type healthApiHealthGetResponse200 = {
  data: unknown
  status: 200
}
    
export type healthApiHealthGetResponseComposite = healthApiHealthGetResponse200;
    
export type healthApiHealthGetResponse = healthApiHealthGetResponseComposite & {
  headers: Headers;
}

export const getHealthApiHealthGetUrl = () => {


  

  return `http://localhost:8000/api/health`
}

export const healthApiHealthGet = async ( options?: RequestInit): Promise<healthApiHealthGetResponse> => {
  
  const res = await fetch(getHealthApiHealthGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: healthApiHealthGetResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as healthApiHealthGetResponse
}



export const getHealthApiHealthGetQueryKey = () => {
    return [`http://localhost:8000/api/health`] as const;
    }

    
export const getHealthApiHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthApiHealthGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthApiHealthGet>>> = ({ signal }) => healthApiHealthGet({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthApiHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthApiHealthGet>>>
export type HealthApiHealthGetQueryError = unknown


/**
 * @summary Health
 */

export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthApiHealthGetQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
